[colors]
foreground= "#DEE0CA"
background= "#3D3A4C"
ansi = [
    "#DEE0CA",
    "#FFC8DC",
    "#A2F0E0",
    "#F3DCA1",
    "#C9DCFF",
    "#F2CFFF",
    "#A4EAFF",
    "#DEDBF1",
]
brights = [
    "#CACDB7",
    "#F7B5C8",
    "#8FDCCC",
    "#DFC98E",
    "#B6C9FF",
    "#DFBBEF",
    "#90D6F2",
    "#CBC7DD",
]

compose_cursor  = "#CACDB7"
cursor_bg       = "#CACDB7"
cursor_border   = "#CACDB7"
cursor_fg       = "#3D3A4C"
selection_bg    = "#4D4F3C"
selection_fg    = "#DEDBF1"
scrollbar_thumb = "#CBC7DD"
split           = "#CBC7DD"

[colors.indexed]

[colors.tab_bar]
background = "#454254"

[colors.tab_bar.active_tab]
bg_color      = "#E8EAD4"
fg_color      = "#3D3A4C"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab]
bg_color      = "#CACDB7"
fg_color      = "#4D4A5C"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color      = "#CACDB7"
fg_color      = "#454254"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab]
bg_color      = "#D4D7C0"
fg_color      = "#454254"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab_hover]
bg_color      = "#DEE0CA"
fg_color      = "#3D3A4C"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[metadata]
aliases = []
author = 'racagogi'
name = "mytilus_dark"
