[colors]
foreground= "#DEDCE7"
background= "#33342B"
ansi = [
    "#DEDCE7",
    "#FCD2D3",
    "#BBEBD5",
    "#EBDEAE",
    "#D1DFF7",
    "#EBD6EC",
    "#BBE7EE",
    "#DEDFD4",
]
brights = [
    "#C4C2CD",
    "#EBB3B9",
    "#91D5BC",
    "#D6C485",
    "#B2C4EA",
    "#D5B9DB",
    "#92D0DD",
    "#C4C5BA",
]

compose_cursor  = "#C4C2CD"
cursor_bg       = "#C4C2CD"
cursor_border   = "#C4C2CD"
cursor_fg       = "#33342B"
selection_bg    = "#48464F"
selection_fg    = "#DEDFD4"
scrollbar_thumb = "#C4C5BA"
split           = "#C4C5BA"

[colors.indexed]

[colors.tab_bar]
background = "#3D3E35"

[colors.tab_bar.active_tab]
bg_color      = "#EBEAF5"
fg_color      = "#33342B"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab]
bg_color      = "#C4C2CD"
fg_color      = "#48493F"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color      = "#C4C2CD"
fg_color      = "#3D3E35"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab]
bg_color      = "#D1CFDA"
fg_color      = "#3D3E35"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab_hover]
bg_color      = "#DEDCE7"
fg_color      = "#33342B"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[metadata]
aliases = []
author = 'racagogi'
name = "mytilus_dark"
