[colors]
foreground= "#D4D5CA"
background= "#363344"
ansi = [
    "#D4D5CA",
    "#F7C4D2",
    "#A9E2D6",
    "#E3D3A8",
    "#C5D3FD",
    "#E3C9F0",
    "#AADDF2",
    "#D4D3DE",
]
brights = [
    "#CACCC1",
    "#F5B7C8",
    "#93DBCC",
    "#DDC992",
    "#B7C9FC",
    "#DDBCED",
    "#95D6F0",
    "#CAC9D4",
]

compose_cursor  = "#CACCC1"
cursor_bg       = "#CACCC1"
cursor_border   = "#CACCC1"
cursor_fg       = "#363344"
selection_bg    = "#525441"
selection_fg    = "#D4D3DE"
scrollbar_thumb = "#CAC9D4"
split           = "#CAC9D4"

[colors.indexed]

[colors.tab_bar]
background = "#3D3A4C"

[colors.tab_bar.active_tab]
bg_color      = "#E1E2D7"
fg_color      = "#363344"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab]
bg_color      = "#CACCC1"
fg_color      = "#535062"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color      = "#CACCC1"
fg_color      = "#3D3A4C"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab]
bg_color      = "#CECFC4"
fg_color      = "#3D3A4C"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab_hover]
bg_color      = "#D4D5CA"
fg_color      = "#363344"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[metadata]
aliases = []
author = 'racagogi'
name = "mytilus_dark"
