[colors]
foreground= "#DBDBD4"
background= "#35343A"
ansi = [
    "#DBDBD4",
    "#F8CED9",
    "#B8E6DC",
    "#E7DAB6",
    "#CEDAFD",
    "#E8D1F2",
    "#B8E2F4",
    "#DBDAE1",
]
brights = [
    "#CECEC7",
    "#F5BBCC",
    "#9BDDCF",
    "#DFCC99",
    "#BCCCFD",
    "#DFC1EE",
    "#9CD8F0",
    "#CECDD4",
]

compose_cursor  = "#CECEC7"
cursor_bg       = "#CECEC7"
cursor_border   = "#CECEC7"
cursor_fg       = "#35343A"
selection_bg    = "#52534D"
selection_fg    = "#DBDAE1"
scrollbar_thumb = "#CECDD4"
split           = "#CECDD4"

[colors.indexed]

[colors.tab_bar]
background = "#403F45"

[colors.tab_bar.active_tab]
bg_color      = "#E1E2DB"
fg_color      = "#35343A"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab]
bg_color      = "#CECEC7"
fg_color      = "#525258"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color      = "#CECEC7"
fg_color      = "#403F45"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab]
bg_color      = "#D4D5CE"
fg_color      = "#403F45"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab_hover]
bg_color      = "#DBDBD4"
fg_color      = "#35343A"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[metadata]
aliases = []
author = 'racagogi'
name = "mytilus_dark"
