[colors]
foreground= "#D5CED8"
background= "#252F20"
ansi = [
    "#D5CED8",
    "#F2C1D7",
    "#B3DAD9",
    "#E1CEB4",
    "#C8CDF9",
    "#E1C5EF",
    "#B4D6F1",
    "#CDD3CA",
]
brights = [
    "#C1BBC4",
    "#E3ABC3",
    "#98C9C6",
    "#D0BA9A",
    "#B3BAEC",
    "#D0B0DF",
    "#99C4E2",
    "#BAC0B6",
]

compose_cursor  = "#C1BBC4"
cursor_bg       = "#C1BBC4"
cursor_border   = "#C1BBC4"
cursor_fg       = "#252F20"
selection_bg    = "#463B4B"
selection_fg    = "#CDD3CA"
scrollbar_thumb = "#BAC0B6"
split           = "#BAC0B6"

[colors.indexed]

[colors.tab_bar]
background = "#2F3929"

[colors.tab_bar.active_tab]
bg_color      = "#DFD8E2"
fg_color      = "#252F20"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab]
bg_color      = "#C1BBC4"
fg_color      = "#394333"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color      = "#C1BBC4"
fg_color      = "#2F3929"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab]
bg_color      = "#CBC5CE"
fg_color      = "#2F3929"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab_hover]
bg_color      = "#D5CED8"
fg_color      = "#252F20"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[metadata]
aliases = []
author = 'racagogi'
name = "#mytilus_dark"
