[colors]
foreground= "#DBDDC7"
background= "#363248"
ansi = [
    "#DBDDC7",
    "#F8CED9",
    "#B8E6DC",
    "#E7DAB6",
    "#CEDAFD",
    "#E8D1F2",
    "#B8E2F4",
    "#DBD8ED",
]
brights = [
    "#CED0BA",
    "#F5BBCC",
    "#9BDDCF",
    "#DFCC99",
    "#BCCCFD",
    "#DFC1EE",
    "#9CD8F0",
    "#CECBE0",
]

compose_cursor  = "#CED0BA"
cursor_bg       = "#CED0BA"
cursor_border   = "#CED0BA"
cursor_fg       = "#363248"
selection_bg    = "#53553B"
selection_fg    = "#DBD8ED"
scrollbar_thumb = "#CECBE0"
split           = "#CECBE0"

[colors.indexed]

[colors.tab_bar]
background = "#403C53"

[colors.tab_bar.active_tab]
bg_color      = "#E1E3D4"
fg_color      = "#363248"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab]
bg_color      = "#CED0BA"
fg_color      = "#534F67"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color      = "#CED0BA"
fg_color      = "#403C53"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab]
bg_color      = "#D4D7C0"
fg_color      = "#403C53"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab_hover]
bg_color      = "#DBDDC7"
fg_color      = "#363248"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[metadata]
aliases = []
author = 'racagogi'
name = "mytilus_dark"
