[colors]
foreground= "#DBDCCE"
background= "#363246"
ansi = [
    "#DBDCCE",
    "#F8CED9",
    "#B8E6DC",
    "#E7DAB6",
    "#CEDAFD",
    "#E8D1F2",
    "#B8E2F4",
    "#DBD9E7",
]
brights = [
    "#CECFC1",
    "#F5BBCC",
    "#9BDDCF",
    "#DFCC99",
    "#BCCCFD",
    "#DFC1EE",
    "#9CD8F0",
    "#CECCDA",
]

compose_cursor  = "#CECFC1"
cursor_bg       = "#CECFC1"
cursor_border   = "#CECFC1"
cursor_fg       = "#363246"
selection_bg    = "#53553E"
selection_fg    = "#DBD9E7"
scrollbar_thumb = "#CECCDA"
split           = "#CECCDA"

[colors.indexed]

[colors.tab_bar]
background = "#403C51"

[colors.tab_bar.active_tab]
bg_color      = "#E1E3D4"
fg_color      = "#363246"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab]
bg_color      = "#CECFC1"
fg_color      = "#534F65"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color      = "#CECFC1"
fg_color      = "#403C51"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab]
bg_color      = "#D4D6C7"
fg_color      = "#403C51"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab_hover]
bg_color      = "#DBDCCE"
fg_color      = "#363246"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[metadata]
aliases = []
author = 'racagogi'
name = "mytilus_dark"
