[colors]
foreground= "#2A332E"
background= "#E5CCDB"
ansi = [
    "#2A332E",
    "#551234",
    "#153637",
    "#482705",
    "#322659",
    "#48194D",
    "#183150",
    "#362D33",
]
brights = [
    "#3E4842",
    "#742049",
    "#154F4D",
    "#633B02",
    "#43397A",
    "#62296B",
    "#1B486E",
    "#4B4247",
]

compose_cursor  = "#3E4842"
cursor_bg       = "#3E4842"
cursor_border   = "#3E4842"
cursor_fg       = "#E5CCDB"
selection_bg    = "#A8C2B3"
selection_fg    = "#362D33"
scrollbar_thumb = "#4B4247"
split           = "#4B4247"

[colors.indexed]

[colors.tab_bar]
background = "#D8BFCE"

[colors.tab_bar.active_tab]
bg_color      = "#202924"
fg_color      = "#E5CCDB"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab]
bg_color      = "#3E4842"
fg_color      = "#CBB2C2"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color      = "#3E4842"
fg_color      = "#D8BFCE"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab]
bg_color      = "#343D38"
fg_color      = "#D8BFCE"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab_hover]
bg_color      = "#2A332E"
fg_color      = "#E5CCDB"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[metadata]
aliases = []
author = 'racagogi'
name = "mytilus_light"
