[colors]
foreground= "#3D3C45"
background= "#E1E4CD"
ansi = [
    "#3D3C45",
    "#572F3C",
    "#0C473E",
    "#493B13",
    "#313B5D",
    "#493353",
    "#104355",
    "#3D3E35",
]
brights = [
    "#4D4C55",
    "#6E3B4B",
    "#045A4F",
    "#5D4B14",
    "#3D4A76",
    "#5C4069",
    "#0D556C",
    "#4D4E45",
]

compose_cursor  = "#4D4C55"
cursor_bg       = "#4D4C55"
cursor_border   = "#4D4C55"
cursor_fg       = "#E1E4CD"
selection_bg    = "#C4C1D6"
selection_fg    = "#3D3E35"
scrollbar_thumb = "#4D4E45"
split           = "#4D4E45"

[colors.indexed]

[colors.tab_bar]
background = "#D4D7C0"

[colors.tab_bar.active_tab]
bg_color      = "#35343D"
fg_color      = "#E1E4CD"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab]
bg_color      = "#4D4C55"
fg_color      = "#C4C6B1"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color      = "#4D4C55"
fg_color      = "#D4D7C0"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab]
bg_color      = "#45444D"
fg_color      = "#D4D7C0"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab_hover]
bg_color      = "#3D3C45"
fg_color      = "#E1E4CD"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[metadata]
aliases = []
author = 'racagogi'
name = "mytilus_light"
