[colors]
foreground= "#BFCAC4"
background= "#32202C"
ansi = [
    "#BFCAC4",
    "#FDABCD",
    "#ABD0D0",
    "#E8BE9C",
    "#C8BDFD",
    "#E8B1EE",
    "#ACCAF1",
    "#CEC4CA",
]
brights = [
    "#A6B1AB",
    "#EB8CB3",
    "#82BAB7",
    "#D2A473",
    "#AAA3EE",
    "#D293DC",
    "#84B3E0",
    "#B5AAB1",
]

compose_cursor  = "#A6B1AB"
cursor_bg       = "#A6B1AB"
cursor_border   = "#A6B1AB"
cursor_fg       = "#32202C"
selection_bg    = "#2A4034"
selection_fg    = "#CEC4CA"
scrollbar_thumb = "#B5AAB1"
split           = "#B5AAB1"

[colors.indexed]

[colors.tab_bar]
background = "#3D2936"

[colors.tab_bar.active_tab]
bg_color      = "#CCD7D1"
fg_color      = "#32202C"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab]
bg_color      = "#A6B1AB"
fg_color      = "#473340"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color      = "#A6B1AB"
fg_color      = "#3D2936"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab]
bg_color      = "#B3BEB7"
fg_color      = "#3D2936"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab_hover]
bg_color      = "#BFCAC4"
fg_color      = "#32202C"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[metadata]
aliases = []
author = 'racagogi'
name = "mytilus_dark"
