[colors]
foreground= "#433A40"
background= "#DAE4DD"
ansi = [
    "#433A40",
    "#5E283E",
    "#0F4741",
    "#50380E",
    "#363764",
    "#502D59",
    "#14425B",
    "#37403A",
]
brights = [
    "#534A50",
    "#70384E",
    "#235751",
    "#614820",
    "#454876",
    "#613D6A",
    "#26526C",
    "#47504A",
]

compose_cursor  = "#534A50"
cursor_bg       = "#534A50"
cursor_border   = "#534A50"
cursor_fg       = "#DAE4DD"
selection_bg    = "#CEC4CB"
selection_fg    = "#37403A"
scrollbar_thumb = "#47504A"
split           = "#47504A"

[colors.indexed]

[colors.tab_bar]
background = "#CDD7D0"

[colors.tab_bar.active_tab]
bg_color      = "#3B3338"
fg_color      = "#DAE4DD"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab]
bg_color      = "#534A50"
fg_color      = "#C0CAC3"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color      = "#534A50"
fg_color      = "#CDD7D0"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab]
bg_color      = "#4B4248"
fg_color      = "#CDD7D0"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab_hover]
bg_color      = "#433A40"
fg_color      = "#DAE4DD"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[metadata]
aliases = []
author = 'racagogi'
name = "mytilus_light"
