[colors]
foreground= "#3B3849"
background= "#DEE0CA"
ansi = [
    "#484557",
    "#794153",
    "#415F30",
    "#675317",
    "#445282",
    "#664774",
    "#105E77",
    "#CED0BA",
]
brights = [
    "#555265",
    "#794153",
    "#415F30",
    "#675317",
    "#445282",
    "#664774",
    "#105E77",
    "#EEF1DA",
]

compose_cursor  = "#555265"
cursor_bg       = "#555265"
cursor_border   = "#555265"
cursor_fg       = "#DEE0CA"
selection_bg    = "#BEBBD0"
selection_fg    = "#3B3C2A"
scrollbar_thumb = "#555744"
split           = "#555744"

[colors.indexed]

[colors.tab_bar]
background = "#CED0BA"

[colors.tab_bar.active_tab]
bg_color      = "#2E2B3C"
fg_color      = "#DEE0CA"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab]
bg_color      = "#555265"
fg_color      = "#BEC0AA"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color      = "#555265"
fg_color      = "#CED0BA"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab]
bg_color      = "#484557"
fg_color      = "#CED0BA"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab_hover]
bg_color      = "#3B3849"
fg_color      = "#DEE0CA"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[metadata]
aliases = []
author = 'racagogi'
name = "mytilus_light"
