[colors]
foreground= "#3A3A3F"
background= "#E1E2DB"
ansi = [
    "#3A3A3F",
    "#502F39",
    "#17433B",
    "#45391A",
    "#303955",
    "#44324D",
    "#19404E",
    "#3A3B35",
]
brights = [
    "#45444A",
    "#633443",
    "#025146",
    "#544310",
    "#36436B",
    "#53395F",
    "#094C61",
    "#454640",
]

compose_cursor  = "#45444A"
cursor_bg       = "#45444A"
cursor_border   = "#45444A"
cursor_fg       = "#E1E2DB"
selection_bg    = "#BEBDC4"
selection_fg    = "#3A3B35"
scrollbar_thumb = "#454640"
split           = "#454640"

[colors.indexed]

[colors.tab_bar]
background = "#D4D5CE"

[colors.tab_bar.active_tab]
bg_color      = "#35343A"
fg_color      = "#E1E2DB"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab]
bg_color      = "#45444A"
fg_color      = "#BDBEB7"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color      = "#45444A"
fg_color      = "#D4D5CE"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab]
bg_color      = "#403F45"
fg_color      = "#D4D5CE"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab_hover]
bg_color      = "#3A3A3F"
fg_color      = "#E1E2DB"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[metadata]
aliases = []
author = 'racagogi'
name = "mytilus_light"
