[colors]
foreground= "#3D3C45"
background= "#E4E6DB"
ansi = [
    "#3D3C45",
    "#533334",
    "#1A4736",
    "#483C0F",
    "#323D51",
    "#473748",
    "#1B444A",
    "#3D3E35",
]
brights = [
    "#4D4C55",
    "#6C3D43",
    "#115A46",
    "#5C4C04",
    "#3D4D6C",
    "#5B4360",
    "#145662",
    "#4D4E45",
]

compose_cursor  = "#4D4C55"
cursor_bg       = "#4D4C55"
cursor_border   = "#4D4C55"
cursor_fg       = "#E4E6DB"
selection_bg    = "#CAC9D4"
selection_fg    = "#3D3E35"
scrollbar_thumb = "#4D4E45"
split           = "#4D4E45"

[colors.indexed]

[colors.tab_bar]
background = "#D7D9CE"

[colors.tab_bar.active_tab]
bg_color      = "#33323A"
fg_color      = "#E4E6DB"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab]
bg_color      = "#4D4C55"
fg_color      = "#CACCC1"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color      = "#4D4C55"
fg_color      = "#D7D9CE"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab]
bg_color      = "#42414A"
fg_color      = "#D7D9CE"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab_hover]
bg_color      = "#3D3C45"
fg_color      = "#E4E6DB"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[metadata]
aliases = []
author = 'racagogi'
name = "mytilus_light"
