[colors]
foreground= "#38373F"
background= "#E1E2D7"
ansi = [
    "#38373F",
    "#4F2E23",
    "#0F413C",
    "#393B0D",
    "#383549",
    "#492F3A",
    "#213C4A",
    "#383930",
]
brights = [
    "#4D4C55",
    "#6F3E32",
    "#035956",
    "#4E510F",
    "#4E4869",
    "#653F53",
    "#2A526A",
    "#4D4E45",
]

compose_cursor  = "#4D4C55"
cursor_bg       = "#4D4C55"
cursor_border   = "#4D4C55"
cursor_fg       = "#E1E2D7"
selection_bg    = "#C7C6D0"
selection_fg    = "#383930"
scrollbar_thumb = "#4D4E45"
split           = "#4D4E45"

[colors.indexed]

[colors.tab_bar]
background = "#D4D5CA"

[colors.tab_bar.active_tab]
bg_color      = "#2E2D35"
fg_color      = "#E1E2D7"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab]
bg_color      = "#4D4C55"
fg_color      = "#C7C8BD"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color      = "#4D4C55"
fg_color      = "#D4D5CA"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab]
bg_color      = "#42414A"
fg_color      = "#D4D5CA"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab_hover]
bg_color      = "#38373F"
fg_color      = "#E1E2D7"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[metadata]
aliases = []
author = 'racagogi'
name = "mytilus_light"
