[colors]
foreground= "#CBC1C7"
background= "#212924"
ansi = [
    "#CBC1C7",
    "#F1AEC6",
    "#9BD1C9",
    "#DCBF94",
    "#BABFF6",
    "#DCB3E7",
    "#9CCBEA",
    "#BDC7C0",
]
brights = [
    "#B8AEB4",
    "#DD9BB3",
    "#88BDB6",
    "#C9AC82",
    "#A7ACE2",
    "#C8A0D3",
    "#89B8D6",
    "#AAB4AD",
]

compose_cursor  = "#B8AEB4"
cursor_bg       = "#B8AEB4"
cursor_border   = "#B8AEB4"
cursor_fg       = "#212924"
selection_bg    = "#40383D"
selection_fg    = "#BDC7C0"
scrollbar_thumb = "#AAB4AD"
split           = "#AAB4AD"

[colors.indexed]

[colors.tab_bar]
background = "#2A332D"

[colors.tab_bar.active_tab]
bg_color      = "#D5CAD1"
fg_color      = "#212924"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab]
bg_color      = "#B8AEB4"
fg_color      = "#343D37"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color      = "#B8AEB4"
fg_color      = "#2A332D"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab]
bg_color      = "#C1B7BE"
fg_color      = "#2A332D"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab_hover]
bg_color      = "#CBC1C7"
fg_color      = "#212924"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[metadata]
aliases = []
author = 'racagogi'
name = "mytilus_dark"
