[colors]
foreground= "#DBD9E4"
background= "#33342B"
ansi = [
    "#DBD9E4",
    "#FBD0C2",
    "#B5E7E0",
    "#DBE0AF",
    "#DBD7F1",
    "#F2D0DD",
    "#C1E0F2",
    "#DBDCD1",
]
brights = [
    "#C1BFCA",
    "#EBB1A2",
    "#89D0CB",
    "#C1C787",
    "#C1BBE2",
    "#DFB2C8",
    "#9DC7E4",
    "#C1C2B7",
]

compose_cursor  = "#C1BFCA"
cursor_bg       = "#C1BFCA"
cursor_border   = "#C1BFCA"
cursor_fg       = "#33342B"
selection_bg    = "#48464F"
selection_fg    = "#DBDCD1"
scrollbar_thumb = "#C1C2B7"
split           = "#C1C2B7"

[colors.indexed]

[colors.tab_bar]
background = "#3D3E35"

[colors.tab_bar.active_tab]
bg_color      = "#E8E6F1"
fg_color      = "#33342B"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab]
bg_color      = "#C1BFCA"
fg_color      = "#48493F"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color      = "#C1BFCA"
fg_color      = "#3D3E35"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab]
bg_color      = "#CECCD7"
fg_color      = "#3D3E35"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab_hover]
bg_color      = "#DBD9E4"
fg_color      = "#33342B"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[metadata]
aliases = []
author = 'racagogi'
name = "mytilus_dark"
