[colors]
foreground= "#3B3944"
background= "#E1E4CA"
ansi = [
    "#3B3944",
    "#502F39",
    "#17433B",
    "#45391A",
    "#303955",
    "#44324D",
    "#19404E",
    "#3A3C30",
]
brights = [
    "#45434F",
    "#633443",
    "#025146",
    "#544310",
    "#36436B",
    "#53395F",
    "#094C61",
    "#45463A",
]

compose_cursor  = "#45434F"
cursor_bg       = "#45434F"
cursor_border   = "#45434F"
cursor_fg       = "#E1E4CA"
selection_bg    = "#BEBAD3"
selection_fg    = "#3A3C30"
scrollbar_thumb = "#45463A"
split           = "#45463A"

[colors.indexed]

[colors.tab_bar]
background = "#D4D7BD"

[colors.tab_bar.active_tab]
bg_color      = "#35343F"
fg_color      = "#E1E4CA"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab]
bg_color      = "#45434F"
fg_color      = "#BEC0A7"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color      = "#45434F"
fg_color      = "#D4D7BD"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab]
bg_color      = "#403E4A"
fg_color      = "#D4D7BD"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab_hover]
bg_color      = "#3B3944"
fg_color      = "#E1E4CA"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[metadata]
aliases = []
author = 'racagogi'
name = "mytilus_light"
