[colors]
foreground= "#3B363D"
background= "#DAE0D6"
ansi = [
    "#3B363D",
    "#4E2B3C",
    "#203E3E",
    "#433523",
    "#333455",
    "#442E4D",
    "#213B4F",
    "#353A32",
]
brights = [
    "#4B454D",
    "#63384C",
    "#27504F",
    "#56442B",
    "#40446B",
    "#563C62",
    "#294C63",
    "#444A42",
]

compose_cursor  = "#4B454D"
cursor_bg       = "#4B454D"
cursor_border   = "#4B454D"
cursor_fg       = "#DAE0D6"
selection_bg    = "#C8C1CB"
selection_fg    = "#353A32"
scrollbar_thumb = "#444A42"
split           = "#444A42"

[colors.indexed]

[colors.tab_bar]
background = "#CDD3CA"

[colors.tab_bar.active_tab]
bg_color      = "#332E36"
fg_color      = "#DAE0D6"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab]
bg_color      = "#4B454D"
fg_color      = "#C0C6BD"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color      = "#4B454D"
fg_color      = "#CDD3CA"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab]
bg_color      = "#433D45"
fg_color      = "#CDD3CA"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab_hover]
bg_color      = "#3B363D"
fg_color      = "#DAE0D6"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[metadata]
aliases = []
author = 'racagogi'
name = "mytilus_light"
