[colors]
foreground= "#3D3A4C"
background= "#DEE0CA"
ansi = [
    "#3D3A4C",
    "#5E293B",
    "#004A3F",
    "#4D3A00",
    "#2D3A67",
    "#4D2F5A",
    "#00455C",
    "#3D3F2D",
]
brights = [
    "#4D4A5C",
    "#70394B",
    "#005B4F",
    "#5E4B0C",
    "#3C4A79",
    "#5D3F6B",
    "#00566E",
    "#4D4F3C",
]

compose_cursor  = "#4D4A5C"
cursor_bg       = "#4D4A5C"
cursor_border   = "#4D4A5C"
cursor_fg       = "#DEE0CA"
selection_bg    = "#CBC7DD"
selection_fg    = "#3D3F2D"
scrollbar_thumb = "#4D4F3C"
split           = "#4D4F3C"

[colors.indexed]

[colors.tab_bar]
background = "#D4D7C0"

[colors.tab_bar.active_tab]
bg_color      = "#363344"
fg_color      = "#DEE0CA"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab]
bg_color      = "#4D4A5C"
fg_color      = "#CACDB7"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color      = "#4D4A5C"
fg_color      = "#D4D7C0"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab]
bg_color      = "#454254"
fg_color      = "#D4D7C0"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab_hover]
bg_color      = "#3D3A4C"
fg_color      = "#DEE0CA"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[metadata]
aliases = []
author = 'racagogi'
name = "mytilus_light"
