[colors]
foreground= "#DCD9E4"
background= "#35362E"
ansi = [
    "#DCD9E4",
    "#FECCCF",
    "#B0EAD2",
    "#EADBA3",
    "#CBDBFA",
    "#EAD1ED",
    "#B0E5F0",
    "#DBDCD1",
]
brights = [
    "#C8C5D0",
    "#EFB6BC",
    "#94D8BF",
    "#D9C788",
    "#B5C8ED",
    "#D9BCDE",
    "#95D3E1",
    "#C7C8BD",
]

compose_cursor  = "#D2CFDA"
cursor_bg       = "#D2CFDA"
cursor_border   = "#D2CFDA"
cursor_fg       = "#2B2C24"
selection_bg    = "#4A4B42"
selection_fg    = "#DBDCD1"
scrollbar_thumb = "#C7C8BD"
split           = "#C7C8BD"

[colors.indexed]

[colors.tab_bar]
background = "#403E47"

[colors.tab_bar.active_tab]
bg_color      = "#E5E3EE"
fg_color      = "#35362E"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab]
bg_color      = "#C8C5D0"
fg_color      = "#4A4B42"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color      = "#C8C5D0"
fg_color      = "#404138"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab]
bg_color      = "#D2CFDA"
fg_color      = "#404138"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab_hover]
bg_color      = "#DCD9E4"
fg_color      = "#35362E"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[metadata]
aliases = []
author = 'racagogi'
name = "mytilus_dark"
