[colors]
foreground= "#433D45"
background= "#E0EDD9"
ansi = [
    "#433D45",
    "#583244",
    "#234746",
    "#4D3D27",
    "#393C60",
    "#4D3557",
    "#254359",
    "#3C423A",
]
brights = [
    "#534D56",
    "#6D3F54",
    "#2B5957",
    "#5F4C2F",
    "#474B76",
    "#5F436C",
    "#2D546E",
    "#4C524A",
]

compose_cursor  = "#534D56"
cursor_bg       = "#534D56"
cursor_border   = "#534D56"
cursor_fg       = "#E0EDD9"
selection_bg    = "#D5C8DC"
selection_fg    = "#3C423A"
scrollbar_thumb = "#4C524A"
split           = "#4C524A"

[colors.indexed]

[colors.tab_bar]
background = "#D2E0CC"

[colors.tab_bar.active_tab]
bg_color      = "#3B363D"
fg_color      = "#E0EDD9"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab]
bg_color      = "#534D56"
fg_color      = "#C6D2BF"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color      = "#534D56"
fg_color      = "#D2E0CC"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab]
bg_color      = "#4B454D"
fg_color      = "#D2E0CC"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab_hover]
bg_color      = "#433D45"
fg_color      = "#E0EDD9"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[metadata]
aliases = []
author = 'racagogi'
name = "#mytilus_light"
