[colors]
foreground= "#403E47"
background= "#E8EBD0"
ansi = [
    "#403E47",
    "#5B303E",
    "#054B41",
    "#4D3E10",
    "#323E62",
    "#4D3557",
    "#0B4759",
    "#404138",
]
brights = [
    "#504E58",
    "#713D4E",
    "#0A5D51",
    "#604E17",
    "#404D79",
    "#5F436C",
    "#11586F",
    "#505147",
]

compose_cursor  = "#504E58"
cursor_bg       = "#504E58"
cursor_border   = "#504E58"
cursor_fg       = "#E8EBD0"
selection_bg    = "#CECAE3"
selection_fg    = "#404138"
scrollbar_thumb = "#505147"
split           = "#505147"

[colors.indexed]

[colors.tab_bar]
background = "#DBDEC3"

[colors.tab_bar.active_tab]
bg_color      = "#38373F"
fg_color      = "#E8EBD0"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab]
bg_color      = "#504E58"
fg_color      = "#CED1B7"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color      = "#504E58"
fg_color      = "#DBDEC3"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab]
bg_color      = "#48464F"
fg_color      = "#DBDEC3"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab_hover]
bg_color      = "#403E47"
fg_color      = "#E8EBD0"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[metadata]
aliases = []
author = 'racagogi'
name = "mytilus_light"
