[colors]
foreground= "#D8D1DB"
background= "#2B3028"
ansi = [
    "#D8D1DB",
    "#F2C6DA",
    "#BADCDC",
    "#E3D1BB",
    "#CDD1FA",
    "#E3C9F0",
    "#BAD9F2",
    "#D0D7CD",
]
brights = [
    "#C5BEC8",
    "#E3B0C6",
    "#9FCBC9",
    "#D2BEA1",
    "#B7BDEC",
    "#D2B4E0",
    "#A0C7E3",
    "#BDC3BA",
]

compose_cursor  = "#C5BEC8"
cursor_bg       = "#C5BEC8"
cursor_border   = "#C5BEC8"
cursor_fg       = "#2B3028"
selection_bg    = "#454048"
selection_fg    = "#D0D7CD"
scrollbar_thumb = "#BDC3BA"
split           = "#BDC3BA"

[colors.indexed]

[colors.tab_bar]
background = "#353A32"

[colors.tab_bar.active_tab]
bg_color      = "#E2DBE5"
fg_color      = "#2B3028"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab]
bg_color      = "#C5BEC8"
fg_color      = "#3F443C"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color      = "#C5BEC8"
fg_color      = "#353A32"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab]
bg_color      = "#CEC8D1"
fg_color      = "#353A32"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab_hover]
bg_color      = "#D8D1DB"
fg_color      = "#2B3028"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[metadata]
aliases = []
author = 'racagogi'
name = "mytilus_dark"
