[colors]
foreground= "#D1D2C7"
background= "#2C283B"
ansi = [
    "#D1D2C7",
    "#F6C0CF",
    "#A2E0D2",
    "#E1D0A1",
    "#C0D0FD",
    "#E1C5EF",
    "#A3DBF1",
    "#D1CFDA",
]
brights = [
    "#BDBFB4",
    "#E7AABC",
    "#86CEBF",
    "#D0BC86",
    "#ABBCEF",
    "#D0B0DF",
    "#88C9E2",
    "#BEBCC7",
]

compose_cursor  = "#BDBFB4"
cursor_bg       = "#BDBFB4"
cursor_border   = "#BDBFB4"
cursor_fg       = "#2C283B"
selection_bg    = "#40422C"
selection_fg    = "#D1CFDA"
scrollbar_thumb = "#BEBCC7"
split           = "#BEBCC7"

[colors.indexed]

[colors.tab_bar]
background = "#363246"

[colors.tab_bar.active_tab]
bg_color      = "#DBDCD1"
fg_color      = "#2C283B"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab]
bg_color      = "#BDBFB4"
fg_color      = "#403C51"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color      = "#BDBFB4"
fg_color      = "#363246"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab]
bg_color      = "#C7C8BE"
fg_color      = "#363246"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab_hover]
bg_color      = "#D1D2C7"
fg_color      = "#2C283B"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[metadata]
aliases = []
author = 'racagogi'
name = "mytilus_dark"
