[colors]
foreground= "#D5D2DD"
background= "#2E2F26"
ansi = [
    "#D5D2DD",
    "#F4C7C9",
    "#ADE2CC",
    "#E2D4A1",
    "#C6D5F0",
    "#E2CCE4",
    "#AEDEE6",
    "#D4D5CA",
]
brights = [
    "#BEBCC6",
    "#E5ADB2",
    "#8BCEB6",
    "#CFBD7E",
    "#ACBEE3",
    "#CFB2D4",
    "#8CC9D7",
    "#BEBFB4",
]

compose_cursor  = "#BEBCC6"
cursor_bg       = "#BEBCC6"
cursor_border   = "#BEBCC6"
cursor_fg       = "#2E2F26"
selection_bg    = "#43414A"
selection_fg    = "#D4D5CA"
scrollbar_thumb = "#BEBFB4"
split           = "#BEBFB4"

[colors.indexed]

[colors.tab_bar]
background = "#383930"

[colors.tab_bar.active_tab]
bg_color      = "#DFDCE7"
fg_color      = "#2E2F26"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab]
bg_color      = "#BEBCC6"
fg_color      = "#42433A"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color      = "#BEBCC6"
fg_color      = "#383930"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab]
bg_color      = "#C8C5D0"
fg_color      = "#383930"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab_hover]
bg_color      = "#D5D2DD"
fg_color      = "#2E2F26"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[metadata]
aliases = []
author = 'racagogi'
name = "mytilus_dark"
