[colors]
foreground= "#DEDCE7"
background= "#35362E"
ansi = [
    "#DEDCE7",
    "#FED3C5",
    "#B8EAE3",
    "#DEE3B2",
    "#DEDAF4",
    "#F5D3E0",
    "#C4E3F5",
    "#DEDFD4",
]
brights = [
    "#C4C2CD",
    "#EFB4A5",
    "#8CD3CF",
    "#C4CA8A",
    "#C5BEE5",
    "#E3B5CB",
    "#A0CBE7",
    "#C4C5BA",
]

compose_cursor  = "#C4C2CD"
cursor_bg       = "#C4C2CD"
cursor_border   = "#C4C2CD"
cursor_fg       = "#35362E"
selection_bg    = "#4D4C55"
selection_fg    = "#DEDFD4"
scrollbar_thumb = "#C4C5BA"
split           = "#C4C5BA"

[colors.indexed]

[colors.tab_bar]
background = "#42433A"

[colors.tab_bar.active_tab]
bg_color      = "#EBEAF5"
fg_color      = "#35362E"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab]
bg_color      = "#C4C2CD"
fg_color      = "#4D4E45"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color      = "#C4C2CD"
fg_color      = "#42433A"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab]
bg_color      = "#D1CFDA"
fg_color      = "#42433A"
intensity     = 'Normal'
italic        = false
strikethrough = false
underline     = 'None'

[colors.tab_bar.new_tab_hover]
bg_color      = "#DEDCE7"
fg_color      = "#35362E"
intensity     = 'Normal'
italic        = true
strikethrough = false
underline     = 'None'

[metadata]
aliases = []
author = 'racagogi'
name = "mytilus_dark"
