[colors]
background                      = "#E1E2D7"
dim-foreground                  = "#2E2D35"
foreground                      = "#38373F"
light-foreground                = "#4D4C55"

black                           = "#38373F"
red                             = "#4F2E23"
green                           = "#0F413C"
yellow                          = "#393B0D"
blue                            = "#383549"
magenta                         = "#492F3A"
cyan                            = "#213C4A"
white                           = "#383930"

dim-black                       = "#2E2D35"
dim-red                         = "#4F2E23"
dim-green                       = "#0F413C"
dim-yellow                      = "#393B0D"
dim-blue                        = "#383549"
dim-magenta                     = "#492F3A"
dim-cyan                        = "#213C4A"
dim-white                       = "#2E2F26"

light-black                     = "#4D4C55"
light-red                       = "#6F3E32"
light-green                     = "#035956"
light-yellow                    = "#4E510F"
light-blue                      = "#4E4869"
light-magenta                   = "#653F53"
light-cyan                      = "#2A526A"
light-white                     = "#4D4E45"

cursor                          = "#4D4C55"
vi-cursor                       = "#035956"

tabs                            = "#4D4C55"
tabs-active                     = "#2E2D35"
tabs-active-highlight           = "#2E2D35"
tabs-active-foreground          = "#E1E2D7"
tabs-foreground                 = "#4D4C55"
bar                             = "#D1D2C7"

search-match-background         = "#D1D79E"
search-match-foreground         = "#383930"
search-focused-match-background = "#ECCB9D"
search-focused-match-foreground = "#383930"

selection-background            = "#D1CFDA"
selection-foreground            = "#383930"
