[colors]
background                      = "#212924"
dim-foreground                  = "#D5CAD1"
foreground                      = "#CBC1C7"
light-foreground                = "#B8AEB4"

black                           = "#CBC1C7"
red                             = "#F1AEC6"
green                           = "#9BD1C9"
yellow                          = "#DCBF94"
blue                            = "#BABFF6"
magenta                         = "#DCB3E7"
cyan                            = "#9CCBEA"
white                           = "#BDC7C0"

dim-black                       = "#D5CAD1"
dim-red                         = "#F1AEC6"
dim-green                       = "#9BD1C9"
dim-yellow                      = "#DCBF94"
dim-blue                        = "#BABFF6"
dim-magenta                     = "#DCB3E7"
dim-cyan                        = "#9CCBEA"
dim-white                       = "#C6D1CA"

light-black                     = "#B8AEB4"
light-red                       = "#DD9BB3"
light-green                     = "#88BDB6"
light-yellow                    = "#C9AC82"
light-blue                      = "#A7ACE2"
light-magenta                   = "#C8A0D3"
light-cyan                      = "#89B8D6"
light-white                     = "#AAB4AD"

cursor                          = "#B8AEB4"
vi-cursor                       = "#88BDB6"

tabs                            = "#B8AEB4"
tabs-active                     = "#D5CAD1"
tabs-active-highlight           = "#D5CAD1"
tabs-active-foreground          = "#212924"
tabs-foreground                 = "#B8AEB4"
bar                             = "#2A332D"

search-match-background         = "#333213"
search-match-foreground         = "#BDC7C0"
search-focused-match-background = "#3D2D1C"
search-focused-match-foreground = "#BDC7C0"

selection-background            = "#362D33"
selection-foreground            = "#BDC7C0"
