[colors]
background                      = "#DAE4DD"
dim-foreground                  = "#3B3338"
foreground                      = "#433A40"
light-foreground                = "#534A50"

black                           = "#433A40"
red                             = "#5E283E"
green                           = "#0F4741"
yellow                          = "#50380E"
blue                            = "#363764"
magenta                         = "#502D59"
cyan                            = "#14425B"
white                           = "#37403A"

dim-black                       = "#3B3338"
dim-red                         = "#5E283E"
dim-green                       = "#0F4741"
dim-yellow                      = "#50380E"
dim-blue                        = "#363764"
dim-magenta                     = "#502D59"
dim-cyan                        = "#14425B"
dim-white                       = "#2F3832"

light-black                     = "#534A50"
light-red                       = "#70384E"
light-green                     = "#235751"
light-yellow                    = "#614820"
light-blue                      = "#454876"
light-magenta                   = "#613D6A"
light-cyan                      = "#26526C"
light-white                     = "#47504A"

cursor                          = "#534A50"
vi-cursor                       = "#235751"

tabs                            = "#534A50"
tabs-active                     = "#3B3338"
tabs-active-highlight           = "#3B3338"
tabs-active-foreground          = "#DAE4DD"
tabs-foreground                 = "#534A50"
bar                             = "#CDD7D0"

search-match-background         = "#D7D7B3"
search-match-foreground         = "#37403A"
search-focused-match-background = "#E5D0BB"
search-focused-match-foreground = "#37403A"

selection-background            = "#DBD1D8"
selection-foreground            = "#37403A"
