[colors]
background                      = "#E1E4CD"
dim-foreground                  = "#35343D"
foreground                      = "#3D3C45"
light-foreground                = "#4D4C55"

black                           = "#3D3C45"
red                             = "#572F3C"
green                           = "#0C473E"
yellow                          = "#493B13"
blue                            = "#313B5D"
magenta                         = "#493353"
cyan                            = "#104355"
white                           = "#3D3E35"

dim-black                       = "#35343D"
dim-red                         = "#572F3C"
dim-green                       = "#0C473E"
dim-yellow                      = "#493B13"
dim-blue                        = "#313B5D"
dim-magenta                     = "#493353"
dim-cyan                        = "#104355"
dim-white                       = "#35362E"

light-black                     = "#4D4C55"
light-red                       = "#6E3B4B"
light-green                     = "#045A4F"
light-yellow                    = "#5D4B14"
light-blue                      = "#3D4A76"
light-magenta                   = "#5C4069"
light-cyan                      = "#0D556C"
light-white                     = "#4D4E45"

cursor                          = "#4D4C55"
vi-cursor                       = "#045A4F"

tabs                            = "#4D4C55"
tabs-active                     = "#35343D"
tabs-active-highlight           = "#35343D"
tabs-active-foreground          = "#E1E4CD"
tabs-foreground                 = "#4D4C55"
bar                             = "#D4D7C0"

search-match-background         = "#E3D3A8"
search-match-foreground         = "#3D3E35"
search-focused-match-background = "#F7C9B4"
search-focused-match-foreground = "#3D3E35"

selection-background            = "#D4D1E7"
selection-foreground            = "#3D3E35"
