[colors]
background                      = "#363344"
dim-foreground                  = "#E1E2D7"
foreground                      = "#D4D5CA"
light-foreground                = "#CACCC1"

black                           = "#D4D5CA"
red                             = "#F7C4D2"
green                           = "#A9E2D6"
yellow                          = "#E3D3A8"
blue                            = "#C5D3FD"
magenta                         = "#E3C9F0"
cyan                            = "#AADDF2"
white                           = "#D4D3DE"

dim-black                       = "#E1E2D7"
dim-red                         = "#F7C4D2"
dim-green                       = "#A9E2D6"
dim-yellow                      = "#E3D3A8"
dim-blue                        = "#C5D3FD"
dim-magenta                     = "#E3C9F0"
dim-cyan                        = "#AADDF2"
dim-white                       = "#E1E0EB"

light-black                     = "#CACCC1"
light-red                       = "#F5B7C8"
light-green                     = "#93DBCC"
light-yellow                    = "#DDC992"
light-blue                      = "#B7C9FC"
light-magenta                   = "#DDBCED"
light-cyan                      = "#95D6F0"
light-white                     = "#CAC9D4"

cursor                          = "#CACCC1"
vi-cursor                       = "#93DBCC"

tabs                            = "#CACCC1"
tabs-active                     = "#E1E2D7"
tabs-active-highlight           = "#E1E2D7"
tabs-active-foreground          = "#363344"
tabs-foreground                 = "#CACCC1"
bar                             = "#3D3A4C"

search-match-background         = "#493B13"
search-match-foreground         = "#D4D3DE"
search-focused-match-background = "#573222"
search-focused-match-foreground = "#D4D3DE"

selection-background            = "#3D3F2D"
selection-foreground            = "#D4D3DE"
