[colors]
background                      = "#E8EAD4"
dim-foreground                  = "#38373F"
foreground                      = "#403E47"
light-foreground                = "#504E58"

black                           = "#403E47"
red                             = "#5B303E"
green                           = "#054B41"
yellow                          = "#4D3E10"
blue                            = "#323E62"
magenta                         = "#4D3557"
cyan                            = "#0B4759"
white                           = "#404138"

dim-black                       = "#38373F"
dim-red                         = "#5B303E"
dim-green                       = "#054B41"
dim-yellow                      = "#4D3E10"
dim-blue                        = "#323E62"
dim-magenta                     = "#4D3557"
dim-cyan                        = "#0B4759"
dim-white                       = "#383930"

light-black                     = "#504E58"
light-red                       = "#713D4E"
light-green                     = "#0A5D51"
light-yellow                    = "#604E17"
light-blue                      = "#404D79"
light-magenta                   = "#5F436C"
light-cyan                      = "#11586F"
light-white                     = "#505147"

cursor                          = "#504E58"
vi-cursor                       = "#0A5D51"

tabs                            = "#504E58"
tabs-active                     = "#38373F"
tabs-active-highlight           = "#38373F"
tabs-active-foreground          = "#E8EAD4"
tabs-foreground                 = "#504E58"
bar                             = "#DBDDC7"

search-match-background         = "#E7DAB6"
search-match-foreground         = "#404138"
search-focused-match-background = "#F8D1C0"
search-focused-match-foreground = "#404138"

selection-background            = "#DBD8ED"
selection-foreground            = "#404138"
