[colors]
background                      = "#E5CCDB"
dim-foreground                  = "#202924"
foreground                      = "#2A332E"
light-foreground                = "#3E4842"

black                           = "#2A332E"
red                             = "#551234"
green                           = "#153637"
yellow                          = "#482705"
blue                            = "#322659"
magenta                         = "#48194D"
cyan                            = "#183150"
white                           = "#362D33"

dim-black                       = "#202924"
dim-red                         = "#551234"
dim-green                       = "#153637"
dim-yellow                      = "#482705"
dim-blue                        = "#322659"
dim-magenta                     = "#48194D"
dim-cyan                        = "#183150"
dim-white                       = "#2C2429"

light-black                     = "#3E4842"
light-red                       = "#742049"
light-green                     = "#154F4D"
light-yellow                    = "#633B02"
light-blue                      = "#43397A"
light-magenta                   = "#62296B"
light-cyan                      = "#1B486E"
light-white                     = "#4B4247"

cursor                          = "#3E4842"
vi-cursor                       = "#154F4D"

tabs                            = "#3E4842"
tabs-active                     = "#202924"
tabs-active-highlight           = "#202924"
tabs-active-foreground          = "#E5CCDB"
tabs-foreground                 = "#3E4842"
bar                             = "#D8BFCE"

search-match-background         = "#E8BE9C"
search-match-foreground         = "#362D33"
search-focused-match-background = "#FDB1AA"
search-focused-match-foreground = "#362D33"

selection-background            = "#B5CFC0"
selection-foreground            = "#362D33"
