[colors]
background                      = "#E1E5C7"
dim-foreground                  = "#35343F"
foreground                      = "#3B3849"
light-foreground                = "#454254"

black                           = "#3B3849"
red                             = "#502F39"
green                           = "#17433B"
yellow                          = "#45391A"
blue                            = "#303955"
magenta                         = "#44324D"
cyan                            = "#19404E"
white                           = "#3B3C2A"

dim-black                       = "#35343F"
dim-red                         = "#502F39"
dim-green                       = "#17433B"
dim-yellow                      = "#45391A"
dim-blue                        = "#303955"
dim-magenta                     = "#44324D"
dim-cyan                        = "#19404E"
dim-white                       = "#35372B"

light-black                     = "#454254"
light-red                       = "#633443"
light-green                     = "#025146"
light-yellow                    = "#544310"
light-blue                      = "#36436B"
light-magenta                   = "#53395F"
light-cyan                      = "#094C61"
light-white                     = "#454734"

cursor                          = "#454254"
vi-cursor                       = "#025146"

tabs                            = "#454254"
tabs-active                     = "#35343F"
tabs-active-highlight           = "#35343F"
tabs-active-foreground          = "#E1E5C7"
tabs-foreground                 = "#454254"
bar                             = "#D4D7BA"

search-match-background         = "#E3D3A8"
search-match-foreground         = "#3B3C2A"
search-focused-match-background = "#F7C9B4"
search-focused-match-foreground = "#3B3C2A"

selection-background            = "#D4D0ED"
selection-foreground            = "#3B3C2A"
