[colors]
background                      = "#E0EDD9"
dim-foreground                  = "#3B363D"
foreground                      = "#433D45"
light-foreground                = "#534D56"

black                           = "#433D45"
red                             = "#583244"
green                           = "#234746"
yellow                          = "#4D3D27"
blue                            = "#393C60"
magenta                         = "#4D3557"
cyan                            = "#254359"
white                           = "#3C423A"

dim-black                       = "#3B363D"
dim-red                         = "#583244"
dim-green                       = "#234746"
dim-yellow                      = "#4D3D27"
dim-blue                        = "#393C60"
dim-magenta                     = "#4D3557"
dim-cyan                        = "#254359"
dim-white                       = "#353A32"

light-black                     = "#534D56"
light-red                       = "#6D3F54"
light-green                     = "#2B5957"
light-yellow                    = "#5F4C2F"
light-blue                      = "#474B76"
light-magenta                   = "#5F436C"
light-cyan                      = "#2D546E"
light-white                     = "#4C524A"

cursor                          = "#534D56"
vi-cursor                       = "#2B5957"

tabs                            = "#534D56"
tabs-active                     = "#3B363D"
tabs-active-highlight           = "#3B363D"
tabs-active-foreground          = "#E0EDD9"
tabs-foreground                 = "#534D56"
bar                             = "#D2E0CC"

search-match-background         = "#DBDFB5"
search-match-foreground         = "#3C423A"
search-focused-match-background = "#E6DABC"
search-focused-match-foreground = "#3C423A"

selection-background            = "#E2D5E9"
selection-foreground            = "#3C423A"
