[colors]
background                      = "#33342B"
dim-foreground                  = "#E8E6F1"
foreground                      = "#DBD9E4"
light-foreground                = "#C1BFCA"

black                           = "#DBD9E4"
red                             = "#FBD0C2"
green                           = "#B5E7E0"
yellow                          = "#DBE0AF"
blue                            = "#DBD7F1"
magenta                         = "#F2D0DD"
cyan                            = "#C1E0F2"
white                           = "#DBDCD1"

dim-black                       = "#E8E6F1"
dim-red                         = "#FBD0C2"
dim-green                       = "#B5E7E0"
dim-yellow                      = "#DBE0AF"
dim-blue                        = "#DBD7F1"
dim-magenta                     = "#F2D0DD"
dim-cyan                        = "#C1E0F2"
dim-white                       = "#E8E9DE"

light-black                     = "#C1BFCA"
light-red                       = "#EBB1A2"
light-green                     = "#89D0CB"
light-yellow                    = "#C1C787"
light-blue                      = "#C1BBE2"
light-magenta                   = "#DFB2C8"
light-cyan                      = "#9DC7E4"
light-white                     = "#C1C2B7"

cursor                          = "#C1BFCA"
vi-cursor                       = "#89D0CB"

tabs                            = "#C1BFCA"
tabs-active                     = "#E8E6F1"
tabs-active-highlight           = "#E8E6F1"
tabs-active-foreground          = "#33342B"
tabs-foreground                 = "#C1BFCA"
bar                             = "#404138"

search-match-background         = "#41430B"
search-match-foreground         = "#DBDCD1"
search-focused-match-background = "#553A0A"
search-focused-match-foreground = "#DBDCD1"

selection-background            = "#403E47"
selection-foreground            = "#DBDCD1"
