[colors]
background                      = "#E4E6DB"
dim-foreground                  = "#33323A"
foreground                      = "#3D3C45"
light-foreground                = "#4D4C55"

black                           = "#3D3C45"
red                             = "#533334"
green                           = "#1A4736"
yellow                          = "#483C0F"
blue                            = "#323D51"
magenta                         = "#473748"
cyan                            = "#1B444A"
white                           = "#3D3E35"

dim-black                       = "#33323A"
dim-red                         = "#533334"
dim-green                       = "#1A4736"
dim-yellow                      = "#483C0F"
dim-blue                        = "#323D51"
dim-magenta                     = "#473748"
dim-cyan                        = "#1B444A"
dim-white                       = "#33342B"

light-black                     = "#4D4C55"
light-red                       = "#6C3D43"
light-green                     = "#115A46"
light-yellow                    = "#5C4C04"
light-blue                      = "#3D4D6C"
light-magenta                   = "#5B4360"
light-cyan                      = "#145662"
light-white                     = "#4D4E45"

cursor                          = "#4D4C55"
vi-cursor                       = "#115A46"

tabs                            = "#4D4C55"
tabs-active                     = "#33323A"
tabs-active-highlight           = "#33323A"
tabs-active-foreground          = "#E4E6DB"
tabs-foreground                 = "#4D4C55"
bar                             = "#D7D9CE"

search-match-background         = "#E4D8A8"
search-match-foreground         = "#3D3E35"
search-focused-match-background = "#F5CFB2"
search-focused-match-foreground = "#3D3E35"

selection-background            = "#D7D6E1"
selection-foreground            = "#3D3E35"
