[colors]
background                      = "#33342B"
dim-foreground                  = "#EBEAF5"
foreground                      = "#DEDCE7"
light-foreground                = "#C4C2CD"

black                           = "#DEDCE7"
red                             = "#FCD2D3"
green                           = "#BBEBD5"
yellow                          = "#EBDEAE"
blue                            = "#D1DFF7"
magenta                         = "#EBD6EC"
cyan                            = "#BBE7EE"
white                           = "#DEDFD4"

dim-black                       = "#EBEAF5"
dim-red                         = "#FCD2D3"
dim-green                       = "#BBEBD5"
dim-yellow                      = "#EBDEAE"
dim-blue                        = "#D1DFF7"
dim-magenta                     = "#EBD6EC"
dim-cyan                        = "#BBE7EE"
dim-white                       = "#EBECE1"

light-black                     = "#C4C2CD"
light-red                       = "#EBB3B9"
light-green                     = "#91D5BC"
light-yellow                    = "#D6C485"
light-blue                      = "#B2C4EA"
light-magenta                   = "#D5B9DB"
light-cyan                      = "#92D0DD"
light-white                     = "#C4C5BA"

cursor                          = "#C4C2CD"
vi-cursor                       = "#91D5BC"

tabs                            = "#C4C2CD"
tabs-active                     = "#EBEAF5"
tabs-active-highlight           = "#EBEAF5"
tabs-active-foreground          = "#33342B"
tabs-foreground                 = "#C4C2CD"
bar                             = "#3D3E35"

search-match-background         = "#483C0F"
search-match-foreground         = "#DEDFD4"
search-focused-match-background = "#53351C"
search-focused-match-foreground = "#DEDFD4"

selection-background            = "#3D3C45"
selection-foreground            = "#DEDFD4"
