[colors]
background                      = "#363248"
dim-foreground                  = "#DEDFD7"
foreground                      = "#D4D6C4"
light-foreground                = "#C1C3B1"

black                           = "#D4D6C4"
red                             = "#F4C6D3"
green                           = "#ADE1D5"
yellow                          = "#E2D3AC"
blue                            = "#C6D3F9"
magenta                         = "#E2CAEE"
cyan                            = "#AEDDF0"
white                           = "#D4D2E4"

dim-black                       = "#DEDFD7"
dim-red                         = "#F4C6D3"
dim-green                       = "#ADE1D5"
dim-yellow                      = "#E2D3AC"
dim-blue                        = "#C6D3F9"
dim-magenta                     = "#E2CAEE"
dim-cyan                        = "#AEDDF0"
dim-white                       = "#DEDDE4"

light-black                     = "#C1C3B1"
light-red                       = "#E8AFBF"
light-green                     = "#8ED0C2"
light-yellow                    = "#D2C08D"
light-blue                      = "#AFBFEF"
light-magenta                   = "#D2B4E1"
light-cyan                      = "#8FCBE3"
light-white                     = "#C1BED0"

cursor                          = "#C1C3B1"
vi-cursor                       = "#8ED0C2"

tabs                            = "#C1C3B1"
tabs-active                     = "#DEDFD7"
tabs-active-highlight           = "#DEDFD7"
tabs-active-foreground          = "#363248"
tabs-foreground                 = "#C1C3B1"
bar                             = "#3D3951"

search-match-background         = "#483C18"
search-match-foreground         = "#D4D2E4"
search-focused-match-background = "#553324"
search-focused-match-foreground = "#D4D2E4"

selection-background            = "#3D3F27"
selection-foreground            = "#D4D2E4"
