[colors]
background                      = "#DEE0CA"
dim-foreground                  = "#363344"
foreground                      = "#3D3A4C"
light-foreground                = "#4D4A5C"

black                           = "#3D3A4C"
red                             = "#5E293B"
green                           = "#004A3F"
yellow                          = "#4D3A00"
blue                            = "#2D3A67"
magenta                         = "#4D2F5A"
cyan                            = "#00455C"
white                           = "#3D3F2D"

dim-black                       = "#363344"
dim-red                         = "#5E293B"
dim-green                       = "#004A3F"
dim-yellow                      = "#4D3A00"
dim-blue                        = "#2D3A67"
dim-magenta                     = "#4D2F5A"
dim-cyan                        = "#00455C"
dim-white                       = "#353725"

light-black                     = "#4D4A5C"
light-red                       = "#70394B"
light-green                     = "#005B4F"
light-yellow                    = "#5E4B0C"
light-blue                      = "#3C4A79"
light-magenta                   = "#5D3F6B"
light-cyan                      = "#00566E"
light-white                     = "#4D4F3C"

cursor                          = "#4D4A5C"
vi-cursor                       = "#005B4F"

tabs                            = "#4D4A5C"
tabs-active                     = "#363344"
tabs-active-highlight           = "#363344"
tabs-active-foreground          = "#DEE0CA"
tabs-foreground                 = "#4D4A5C"
bar                             = "#D4D7C0"

search-match-background         = "#E9D397"
search-match-foreground         = "#3D3F2D"
search-focused-match-background = "#FFC4A9"
search-focused-match-foreground = "#3D3F2D"

selection-background            = "#D4D1E7"
selection-foreground            = "#3D3F2D"
