[colors]
background                      = "#35343A"
dim-foreground                  = "#E1E2DB"
foreground                      = "#DBDBD4"
light-foreground                = "#CECEC7"

black                           = "#DBDBD4"
red                             = "#F8CED9"
green                           = "#B8E6DC"
yellow                          = "#E7DAB6"
blue                            = "#CEDAFD"
magenta                         = "#E8D1F2"
cyan                            = "#B8E2F4"
white                           = "#DBDAE1"

dim-black                       = "#E1E2DB"
dim-red                         = "#F8CED9"
dim-green                       = "#B8E6DC"
dim-yellow                      = "#E7DAB6"
dim-blue                        = "#CEDAFD"
dim-magenta                     = "#E8D1F2"
dim-cyan                        = "#B8E2F4"
dim-white                       = "#E1E0E8"

light-black                     = "#CECEC7"
light-red                       = "#F5BBCC"
light-green                     = "#9BDDCF"
light-yellow                    = "#DFCC99"
light-blue                      = "#BCCCFD"
light-magenta                   = "#DFC1EE"
light-cyan                      = "#9CD8F0"
light-white                     = "#CECDD4"

cursor                          = "#CECEC7"
vi-cursor                       = "#9BDDCF"

tabs                            = "#CECEC7"
tabs-active                     = "#E1E2DB"
tabs-active-highlight           = "#E1E2DB"
tabs-active-foreground          = "#35343A"
tabs-foreground                 = "#CECEC7"
bar                             = "#403F45"

search-match-background         = "#4C3E16"
search-match-foreground         = "#DBDAE1"
search-focused-match-background = "#5A3524"
search-focused-match-foreground = "#DBDAE1"

selection-background            = "#40403A"
selection-foreground            = "#DBDAE1"
