[colors]
background                      = "#3D3A4C"
dim-foreground                  = "#E8EAD4"
foreground                      = "#DEE0CA"
light-foreground                = "#CACDB7"

black                           = "#DEE0CA"
red                             = "#FFC8DC"
green                           = "#A2F0E0"
yellow                          = "#F3DCA1"
blue                            = "#C9DCFF"
magenta                         = "#F2CFFF"
cyan                            = "#A4EAFF"
white                           = "#DEDBF1"

dim-black                       = "#E8EAD4"
dim-red                         = "#FFC8DC"
dim-green                       = "#A2F0E0"
dim-yellow                      = "#F3DCA1"
dim-blue                        = "#C9DCFF"
dim-magenta                     = "#F2CFFF"
dim-cyan                        = "#A4EAFF"
dim-white                       = "#E8E5FB"

light-black                     = "#CACDB7"
light-red                       = "#F7B5C8"
light-green                     = "#8FDCCC"
light-yellow                    = "#DFC98E"
light-blue                      = "#B6C9FF"
light-magenta                   = "#DFBBEF"
light-cyan                      = "#90D6F2"
light-white                     = "#CBC7DD"

cursor                          = "#CACDB7"
vi-cursor                       = "#8FDCCC"

tabs                            = "#CACDB7"
tabs-active                     = "#E8EAD4"
tabs-active-highlight           = "#E8EAD4"
tabs-active-foreground          = "#3D3A4C"
tabs-foreground                 = "#CACDB7"
bar                             = "#454254"

search-match-background         = "#564200"
search-match-foreground         = "#DEDBF1"
search-focused-match-background = "#68351E"
search-focused-match-foreground = "#DEDBF1"

selection-background            = "#454734"
selection-foreground            = "#DEDBF1"
