[colors]
background                      = "#363248"
dim-foreground                  = "#E1E3D4"
foreground                      = "#DBDDC7"
light-foreground                = "#CED0BA"

black                           = "#DBDDC7"
red                             = "#F8CED9"
green                           = "#B8E6DC"
yellow                          = "#E7DAB6"
blue                            = "#CEDAFD"
magenta                         = "#E8D1F2"
cyan                            = "#B8E2F4"
white                           = "#DBD8ED"

dim-black                       = "#E1E3D4"
dim-red                         = "#F8CED9"
dim-green                       = "#B8E6DC"
dim-yellow                      = "#E7DAB6"
dim-blue                        = "#CEDAFD"
dim-magenta                     = "#E8D1F2"
dim-cyan                        = "#B8E2F4"
dim-white                       = "#E1DFEE"

light-black                     = "#CED0BA"
light-red                       = "#F5BBCC"
light-green                     = "#9BDDCF"
light-yellow                    = "#DFCC99"
light-blue                      = "#BCCCFD"
light-magenta                   = "#DFC1EE"
light-cyan                      = "#9CD8F0"
light-white                     = "#CECBE0"

cursor                          = "#CED0BA"
vi-cursor                       = "#9BDDCF"

tabs                            = "#CED0BA"
tabs-active                     = "#E1E3D4"
tabs-active-highlight           = "#E1E3D4"
tabs-active-foreground          = "#363248"
tabs-foreground                 = "#CED0BA"
bar                             = "#403C53"

search-match-background         = "#4C3E16"
search-match-foreground         = "#DBD8ED"
search-focused-match-background = "#5A3524"
search-focused-match-foreground = "#DBD8ED"

selection-background            = "#404229"
selection-foreground            = "#DBD8ED"
