[colors]
background                      = "#E1E2DB"
dim-foreground                  = "#35343A"
foreground                      = "#3A3A3F"
light-foreground                = "#45444A"

black                           = "#3A3A3F"
red                             = "#502F39"
green                           = "#17433B"
yellow                          = "#45391A"
blue                            = "#303955"
magenta                         = "#44324D"
cyan                            = "#19404E"
white                           = "#3A3B35"

dim-black                       = "#35343A"
dim-red                         = "#502F39"
dim-green                       = "#17433B"
dim-yellow                      = "#45391A"
dim-blue                        = "#303955"
dim-magenta                     = "#44324D"
dim-cyan                        = "#19404E"
dim-white                       = "#353630"

light-black                     = "#45444A"
light-red                       = "#633443"
light-green                     = "#025146"
light-yellow                    = "#544310"
light-blue                      = "#36436B"
light-magenta                   = "#53395F"
light-cyan                      = "#094C61"
light-white                     = "#454640"

cursor                          = "#45444A"
vi-cursor                       = "#025146"

tabs                            = "#45444A"
tabs-active                     = "#35343A"
tabs-active-highlight           = "#35343A"
tabs-active-foreground          = "#E1E2DB"
tabs-foreground                 = "#45444A"
bar                             = "#D4D5CE"

search-match-background         = "#E3D3A8"
search-match-foreground         = "#3A3B35"
search-focused-match-background = "#F7C9B4"
search-focused-match-foreground = "#3A3B35"

selection-background            = "#D4D3DA"
selection-foreground            = "#3A3B35"
