[colors]
background                      = "#D4D7BA"
dim-foreground                  = "#2E2D33"
foreground                      = "#353341"
light-foreground                = "#454352"

black                           = "#353341"
red                             = "#4C2934"
green                           = "#093E36"
yellow                          = "#403410"
blue                            = "#2A3452"
magenta                         = "#402C49"
cyan                            = "#0D3B4B"
white                           = "#353728"

dim-black                       = "#2E2D33"
dim-red                         = "#4C2934"
dim-green                       = "#093E36"
dim-yellow                      = "#403410"
dim-blue                        = "#2A3452"
dim-magenta                     = "#402C49"
dim-cyan                        = "#0D3B4B"
dim-white                       = "#2E2E29"

light-black                     = "#454352"
light-red                       = "#633443"
light-green                     = "#025146"
light-yellow                    = "#544310"
light-blue                      = "#36436B"
light-magenta                   = "#53395F"
light-cyan                      = "#094C61"
light-white                     = "#454737"

cursor                          = "#454352"
vi-cursor                       = "#025146"

tabs                            = "#454352"
tabs-active                     = "#2E2D33"
tabs-active-highlight           = "#2E2D33"
tabs-active-foreground          = "#D4D7BA"
tabs-foreground                 = "#454352"
bar                             = "#CACEB0"

search-match-background         = "#D8CAA2"
search-match-foreground         = "#353728"
search-focused-match-background = "#EAC0AD"
search-focused-match-foreground = "#353728"

selection-background            = "#CBC6E3"
selection-foreground            = "#353728"
