[colors]
background                      = "#35362E"
dim-foreground                  = "#E5E3EE"
foreground                      = "#DCD9E4"
light-foreground                = "#C8C5D0"

black                           = "#DCD9E4"
red                             = "#FECCCF"
green                           = "#B0EAD2"
yellow                          = "#EADBA3"
blue                            = "#CBDBFA"
magenta                         = "#EAD1ED"
cyan                            = "#B0E5F0"
white                           = "#DBDCD1"

dim-black                       = "#E5E3EE"
dim-red                         = "#FECCCF"
dim-green                       = "#B0EAD2"
dim-yellow                      = "#EADBA3"
dim-blue                        = "#CBDBFA"
dim-magenta                     = "#EAD1ED"
dim-cyan                        = "#B0E5F0"
dim-white                       = "#E4E6DB"

light-black                     = "#C8C5D0"
light-red                       = "#EFB6BC"
light-green                     = "#94D8BF"
light-yellow                    = "#D9C788"
light-blue                      = "#B5C8ED"
light-magenta                   = "#D9BCDE"
light-cyan                      = "#95D3E1"
light-white                     = "#C7C8BD"

cursor                          = "#D2CFDA"
vi-cursor                       = "#94D8BF"

tabs                            = "#D2CFDA"
tabs-active                     = "#D2CFDA"
tabs-active-highlight           = "#D2CFDA"
tabs-active-foreground          = "#2B2C24"
tabs-foreground                 = "#DCD9E4"
bar                             = "#403E47"

search-match-background         = "#334059"
search-match-foreground         = "#DCD9E4"
search-focused-match-background = "#D9BCDE"
search-focused-match-foreground = "#2B2C24"

selection-background            = "#4A4B42"
selection-foreground            = "#DCD9E4"
