[colors]
background                      = "#2E2F26"
dim-foreground                  = "#DFDCE7"
foreground                      = "#D5D2DD"
light-foreground                = "#BEBCC6"

black                           = "#D5D2DD"
red                             = "#F4C7C9"
green                           = "#ADE2CC"
yellow                          = "#E2D4A1"
blue                            = "#C6D5F0"
magenta                         = "#E2CCE4"
cyan                            = "#AEDEE6"
white                           = "#D4D5CA"

dim-black                       = "#DFDCE7"
dim-red                         = "#F4C7C9"
dim-green                       = "#ADE2CC"
dim-yellow                      = "#E2D4A1"
dim-blue                        = "#C6D5F0"
dim-magenta                     = "#E2CCE4"
dim-cyan                        = "#AEDEE6"
dim-white                       = "#DEDFD4"

light-black                     = "#BEBCC6"
light-red                       = "#E5ADB2"
light-green                     = "#8BCEB6"
light-yellow                    = "#CFBD7E"
light-blue                      = "#ACBEE3"
light-magenta                   = "#CFB2D4"
light-cyan                      = "#8CC9D7"
light-white                     = "#BEBFB4"

cursor                          = "#BEBCC6"
vi-cursor                       = "#8BCEB6"

tabs                            = "#BEBCC6"
tabs-active                     = "#DFDCE7"
tabs-active-highlight           = "#DFDCE7"
tabs-active-foreground          = "#2E2F26"
tabs-foreground                 = "#BEBCC6"
bar                             = "#383930"

search-match-background         = "#433701"
search-match-foreground         = "#D4D5CA"
search-focused-match-background = "#502F14"
search-focused-match-foreground = "#D4D5CA"

selection-background            = "#39363F"
selection-foreground            = "#D4D5CA"
