[colors]
background                      = "#252F20"
dim-foreground                  = "#DFD8E2"
foreground                      = "#D5CED8"
light-foreground                = "#C1BBC4"

black                           = "#D5CED8"
red                             = "#F2C1D7"
green                           = "#B3DAD9"
yellow                          = "#E1CEB4"
blue                            = "#C8CDF9"
magenta                         = "#E1C5EF"
cyan                            = "#B4D6F1"
white                           = "#CDD3CA"

dim-black                       = "#DFD8E2"
dim-red                         = "#F2C1D7"
dim-green                       = "#B3DAD9"
dim-yellow                      = "#E1CEB4"
dim-blue                        = "#C8CDF9"
dim-magenta                     = "#E1C5EF"
dim-cyan                        = "#B4D6F1"
dim-white                       = "#D7DDD3"

light-black                     = "#C1BBC4"
light-red                       = "#E3ABC3"
light-green                     = "#98C9C6"
light-yellow                    = "#D0BA9A"
light-blue                      = "#B3BAEC"
light-magenta                   = "#D0B0DF"
light-cyan                      = "#99C4E2"
light-white                     = "#BAC0B6"

cursor                          = "#C1BBC4"
vi-cursor                       = "#98C9C6"

tabs                            = "#C1BBC4"
tabs-active                     = "#DFD8E2"
tabs-active-highlight           = "#DFD8E2"
tabs-active-foreground          = "#252F20"
tabs-foreground                 = "#C1BBC4"
bar                             = "#2F3929"

search-match-background         = "#363814"
search-match-foreground         = "#CDD3CA"
search-focused-match-background = "#3E341B"
search-focused-match-foreground = "#CDD3CA"

selection-background            = "#3B3140"
selection-foreground            = "#CDD3CA"
