[colors]
background                      = "#32202C"
dim-foreground                  = "#CCD7D1"
foreground                      = "#BFCAC4"
light-foreground                = "#A6B1AB"

black                           = "#BFCAC4"
red                             = "#FDABCD"
green                           = "#ABD0D0"
yellow                          = "#E8BE9C"
blue                            = "#C8BDFD"
magenta                         = "#E8B1EE"
cyan                            = "#ACCAF1"
white                           = "#CEC4CA"

dim-black                       = "#CCD7D1"
dim-red                         = "#FDABCD"
dim-green                       = "#ABD0D0"
dim-yellow                      = "#E8BE9C"
dim-blue                        = "#C8BDFD"
dim-magenta                     = "#E8B1EE"
dim-cyan                        = "#ACCAF1"
dim-white                       = "#DBD1D7"

light-black                     = "#A6B1AB"
light-red                       = "#EB8CB3"
light-green                     = "#82BAB7"
light-yellow                    = "#D2A473"
light-blue                      = "#AAA3EE"
light-magenta                   = "#D293DC"
light-cyan                      = "#84B3E0"
light-white                     = "#B5AAB1"

cursor                          = "#A6B1AB"
vi-cursor                       = "#82BAB7"

tabs                            = "#A6B1AB"
tabs-active                     = "#CCD7D1"
tabs-active-highlight           = "#CCD7D1"
tabs-active-foreground          = "#32202C"
tabs-foreground                 = "#A6B1AB"
bar                             = "#3D2936"

search-match-background         = "#482705"
search-match-foreground         = "#CEC4CA"
search-focused-match-background = "#551818"
search-focused-match-foreground = "#CEC4CA"

selection-background            = "#20362A"
selection-foreground            = "#CEC4CA"
