[colors]
background                      = "#E4E6DB"
dim-foreground                  = "#36343C"
foreground                      = "#3E3C44"
light-foreground                = "#4E4B54"

black                           = "#3E3C44"
red                             = "#553234"
green                           = "#144736"
yellow                          = "#493C07"
blue                            = "#313D53"
magenta                         = "#48364A"
cyan                            = "#15444C"
white                           = "#3D3E35"

dim-black                       = "#36343C"
dim-red                         = "#553234"
dim-green                       = "#144736"
dim-yellow                      = "#493C07"
dim-blue                        = "#313D53"
dim-magenta                     = "#48364A"
dim-cyan                        = "#15444C"
dim-white                       = "#35362E"

light-black                     = "#4E4B54"
light-red                       = "#6C3D43"
light-green                     = "#115A46"
light-yellow                    = "#5C4C04"
light-blue                      = "#3D4D6C"
light-magenta                   = "#5B4360"
light-cyan                      = "#145662"
light-white                     = "#4D4E45"

cursor                          = "#4E4B54"
vi-cursor                       = "#115A46"

tabs                            = "#4E4B54"
tabs-active                     = "#36343C"
tabs-active-highlight           = "#36343C"
tabs-active-foreground          = "#E4E6DB"
tabs-foreground                 = "#4E4B54"
bar                             = "#D7D9CE"

search-match-background         = "#E6D8A4"
search-match-foreground         = "#3D3E35"
search-focused-match-background = "#F8CEB0"
search-focused-match-foreground = "#3D3E35"

selection-background            = "#D8D6E0"
selection-foreground            = "#3D3E35"
