[colors]
background                      = "#35362E"
dim-foreground                  = "#EBEAF5"
foreground                      = "#DEDCE7"
light-foreground                = "#C4C2CD"

black                           = "#DEDCE7"
red                             = "#FED3C5"
green                           = "#B8EAE3"
yellow                          = "#DEE3B2"
blue                            = "#DEDAF4"
magenta                         = "#F5D3E0"
cyan                            = "#C4E3F5"
white                           = "#DEDFD4"

dim-black                       = "#EBEAF5"
dim-red                         = "#FED3C5"
dim-green                       = "#B8EAE3"
dim-yellow                      = "#DEE3B2"
dim-blue                        = "#DEDAF4"
dim-magenta                     = "#F5D3E0"
dim-cyan                        = "#C4E3F5"
dim-white                       = "#EBECE1"

light-black                     = "#C4C2CD"
light-red                       = "#EFB4A5"
light-green                     = "#8CD3CF"
light-yellow                    = "#C4CA8A"
light-blue                      = "#C5BEE5"
light-magenta                   = "#E3B5CB"
light-cyan                      = "#A0CBE7"
light-white                     = "#C4C5BA"

cursor                          = "#C4C2CD"
vi-cursor                       = "#8CD3CF"

tabs                            = "#C4C2CD"
tabs-active                     = "#EBEAF5"
tabs-active-highlight           = "#EBEAF5"
tabs-active-foreground          = "#35362E"
tabs-foreground                 = "#C4C2CD"
bar                             = "#42433A"

search-match-background         = "#43460E"
search-match-foreground         = "#DEDFD4"
search-focused-match-background = "#583C0D"
search-focused-match-foreground = "#DEDFD4"

selection-background            = "#42414A"
selection-foreground            = "#DEDFD4"
