[colors]
background                      = "#DEE0CA"
dim-foreground                  = "#2E2B3C"
foreground                      = "#3B3849"
light-foreground                = "#484557"

black                           = "#484557"
red                             = "#794153"
green                           = "#415F30"
yellow                          = "#675317"
blue                            = "#445282"
magenta                         = "#664774"
cyan                            = "#105E77"
white                           = "#CED0BA"

dim-black                       = "#2E2B3C"
dim-red                         = "#794153"
dim-green                       = "#415F30"
dim-yellow                      = "#675317"
dim-blue                        = "#445282"
dim-magenta                     = "#664774"
dim-cyan                        = "#105E77"
dim-white                       = "#BEC0AA"

light-black                     = "#555265"
light-red                       = "#794153"
light-green                     = "#415F30"
light-yellow                    = "#675317"
light-blue                      = "#445282"
light-magenta                   = "#664774"
light-cyan                      = "#105E77"
light-white                     = "#EEF1DA"

cursor                          = "#555265"
vi-cursor                       = "#066357"

tabs                            = "#555265"
tabs-active                     = "#2E2B3C"
tabs-active-highlight           = "#2E2B3C"
tabs-active-foreground          = "#DEE0CA"
tabs-foreground                 = "#555265"
bar                             = "#CED0BA"

search-match-background         = "#D2BC82"
search-match-foreground         = "#3B3C2A"
search-focused-match-background = "#EAAE93"
search-focused-match-foreground = "#3B3C2A"

selection-background            = "#BEBBD0"
selection-foreground            = "#3B3C2A"
