[colors]
background                      = "#DEE0CA"
dim-foreground                  = "#2E2B3C"
foreground                      = "#3B3849"
light-foreground                = "#484557"

black                           = "#3B3849"
red                             = "#794153"
green                           = "#066357"
yellow                          = "#675317"
blue                            = "#445282"
magenta                         = "#664774"
cyan                            = "#105E77"
white                           = "#3B3C2A"

dim-black                       = "#2E2B3C"
dim-red                         = "#794153"
dim-green                       = "#066357"
dim-yellow                      = "#675317"
dim-blue                        = "#445282"
dim-magenta                     = "#664774"
dim-cyan                        = "#105E77"
dim-white                       = "#2E2F1E"

light-black                     = "#484557"
light-red                       = "#794153"
light-green                     = "#066357"
light-yellow                    = "#675317"
light-blue                      = "#445282"
light-magenta                   = "#664774"
light-cyan                      = "#105E77"
light-white                     = "#484A37"

cursor                          = "#555265"
vi-cursor                       = "$(d3_mint)"

tabs                            = "#555265"
tabs-active                     = "#2E2B3C"
tabs-active-highlight           = "#2E2B3C"
tabs-active-foreground          = "#DEE0CA"
tabs-foreground                 = "#555265"
bar                             = "#CED0BA"

search-match-background         = "#D2BC82"
search-match-foreground         = "#3B3C2A"
search-focused-match-background = "#EAAE93"
search-focused-match-foreground = "#3B3C2A"

selection-background            = "#BEBBD0"
selection-foreground            = "#3B3C2A"
