[colors]
background                      = "#DAE0D6"
dim-foreground                  = "#332E36"
foreground                      = "#3B363D"
light-foreground                = "#4B454D"

black                           = "#3B363D"
red                             = "#4E2B3C"
green                           = "#203E3E"
yellow                          = "#433523"
blue                            = "#333455"
magenta                         = "#442E4D"
cyan                            = "#213B4F"
white                           = "#353A32"

dim-black                       = "#332E36"
dim-red                         = "#4E2B3C"
dim-green                       = "#203E3E"
dim-yellow                      = "#433523"
dim-blue                        = "#333455"
dim-magenta                     = "#442E4D"
dim-cyan                        = "#213B4F"
dim-white                       = "#2D322B"

light-black                     = "#4B454D"
light-red                       = "#63384C"
light-green                     = "#27504F"
light-yellow                    = "#56442B"
light-blue                      = "#40446B"
light-magenta                   = "#563C62"
light-cyan                      = "#294C63"
light-white                     = "#444A42"

cursor                          = "#4B454D"
vi-cursor                       = "#27504F"

tabs                            = "#4B454D"
tabs-active                     = "#332E36"
tabs-active-highlight           = "#332E36"
tabs-active-foreground          = "#DAE0D6"
tabs-foreground                 = "#4B454D"
bar                             = "#CDD3CA"

search-match-background         = "#D9D3A8"
search-match-foreground         = "#353A32"
search-focused-match-background = "#E8CBB1"
search-focused-match-foreground = "#353A32"

selection-background            = "#D5CED8"
selection-foreground            = "#353A32"
