[colors]
background                      = "#E8E9DE"
dim-foreground                  = "#39363F"
foreground                      = "#403E47"
light-foreground                = "#504E57"

black                           = "#403E47"
red                             = "#5A3336"
green                           = "#0F4B39"
yellow                          = "#4C3F03"
blue                            = "#334059"
magenta                         = "#4B374E"
cyan                            = "#124850"
white                           = "#404138"

dim-black                       = "#39363F"
dim-red                         = "#5A3336"
dim-green                       = "#0F4B39"
dim-yellow                      = "#4C3F03"
dim-blue                        = "#334059"
dim-magenta                     = "#4B374E"
dim-cyan                        = "#124850"
dim-white                       = "#383930"

light-black                     = "#504E57"
light-red                       = "#6F4046"
light-green                     = "#155D49"
light-yellow                    = "#5F4E09"
light-blue                      = "#404F6F"
light-magenta                   = "#5E4663"
light-cyan                      = "#185965"
light-white                     = "#505147"

cursor                          = "#504E57"
vi-cursor                       = "#155D49"

tabs                            = "#504E57"
tabs-active                     = "#39363F"
tabs-active-highlight           = "#39363F"
tabs-active-foreground          = "#E8E9DE"
tabs-foreground                 = "#504E57"
bar                             = "#DBDCD1"

search-match-background         = "#EADBA3"
search-match-foreground         = "#404138"
search-focused-match-background = "#FED0B0"
search-focused-match-foreground = "#404138"

selection-background            = "#DCD9E4"
selection-foreground            = "#404138"
