[colors]
background                      = "#2B2D1B"
dim-foreground                  = "#DBD9E4"
foreground                      = "#D1CFDA"
light-foreground                = "#BEBCC7"

black                           = "#D1CFDA"
red                             = "#F6C0CF"
green                           = "#A2E0D2"
yellow                          = "#E1D0A1"
blue                            = "#C0D0FD"
magenta                         = "#E1C5EF"
cyan                            = "#A3DBF1"
white                           = "#D1D2C7"

dim-black                       = "#DBD9E4"
dim-red                         = "#F6C0CF"
dim-green                       = "#A2E0D2"
dim-yellow                      = "#E1D0A1"
dim-blue                        = "#C0D0FD"
dim-magenta                     = "#E1C5EF"
dim-cyan                        = "#A3DBF1"
dim-white                       = "#DBDCD1"

light-black                     = "#BEBCC7"
light-red                       = "#E7AABC"
light-green                     = "#86CEBF"
light-yellow                    = "#D0BC86"
light-blue                      = "#ABBCEF"
light-magenta                   = "#D0B0DF"
light-cyan                      = "#88C9E2"
light-white                     = "#BDBFB4"

cursor                          = "#BEBCC7"
vi-cursor                       = "#86CEBF"

tabs                            = "#BEBCC7"
tabs-active                     = "#DBD9E4"
tabs-active-highlight           = "#DBD9E4"
tabs-active-foreground          = "#2B2D1B"
tabs-foreground                 = "#BEBCC7"
bar                             = "#353725"

search-match-background         = "#3F3414"
search-match-foreground         = "#D1D2C7"
search-focused-match-background = "#4B2D1F"
search-focused-match-foreground = "#D1D2C7"

selection-background            = "#363344"
selection-foreground            = "#D1D2C7"
