[colors]
background                      = "#2B3028"
dim-foreground                  = "#E2DBE5"
foreground                      = "#D8D1DB"
light-foreground                = "#C5BEC8"

black                           = "#D8D1DB"
red                             = "#F2C6DA"
green                           = "#BADCDC"
yellow                          = "#E3D1BB"
blue                            = "#CDD1FA"
magenta                         = "#E3C9F0"
cyan                            = "#BAD9F2"
white                           = "#D0D7CD"

dim-black                       = "#E2DBE5"
dim-red                         = "#F2C6DA"
dim-green                       = "#BADCDC"
dim-yellow                      = "#E3D1BB"
dim-blue                        = "#CDD1FA"
dim-magenta                     = "#E3C9F0"
dim-cyan                        = "#BAD9F2"
dim-white                       = "#DAE0D6"

light-black                     = "#C5BEC8"
light-red                       = "#E3B0C6"
light-green                     = "#9FCBC9"
light-yellow                    = "#D2BEA1"
light-blue                      = "#B7BDEC"
light-magenta                   = "#D2B4E0"
light-cyan                      = "#A0C7E3"
light-white                     = "#BDC3BA"

cursor                          = "#C5BEC8"
vi-cursor                       = "#9FCBC9"

tabs                            = "#C5BEC8"
tabs-active                     = "#E2DBE5"
tabs-active-highlight           = "#E2DBE5"
tabs-active-foreground          = "#2B3028"
tabs-foreground                 = "#C5BEC8"
bar                             = "#353A32"

search-match-background         = "#3E3912"
search-match-foreground         = "#D0D7CD"
search-focused-match-background = "#49321D"
search-focused-match-foreground = "#D0D7CD"

selection-background            = "#3B363D"
selection-foreground            = "#D0D7CD"
