[colors]
background                      = "$(v1_white)"
dim-foreground                  = "$(d0_black)"
foreground                      = "$(d1_black)"
light-foreground                = "$(d2_black)"

black                           = "$(d2_black)"
red                             = "$(d3_red)"
green                           = "$(d3_green)"
yellow                          = "$(d3_yellow)"
blue                            = "$(d3_blue)"
magenta                         = "$(d3_magenta)"
cyan                            = "$(d3_cyan)"
white                           = "$(v2_white)"

dim-black                       = "$(d0_black)"
dim-red                         = "$(d3_red)"
dim-green                       = "$(d3_green)"
dim-yellow                      = "$(d3_yellow)"
dim-blue                        = "$(d3_blue)"
dim-magenta                     = "$(d3_magenta)"
dim-cyan                        = "$(d3_cyan)"
dim-white                       = "$(v3_white)"

light-black                     = "$(d3_black)"
light-red                       = "$(d3_red)"
light-green                     = "$(d3_green)"
light-yellow                    = "$(d3_yellow)"
light-blue                      = "$(d3_blue)"
light-magenta                   = "$(d3_magenta)"
light-cyan                      = "$(d3_cyan)"
light-white                     = "$(v0_white)"

cursor                          = "$(d3_black)"
vi-cursor                       = "$(d3_mint)"

tabs                            = "$(d3_black)"
tabs-active                     = "$(d0_black)"
tabs-active-highlight           = "$(d0_black)"
tabs-active-foreground          = "$(v1_white)"
tabs-foreground                 = "$(d3_black)"
bar                             = "$(v2_white)"

search-match-background         = "$(v3_yellow)"
search-match-foreground         = "$(d1_white)"
search-focused-match-background = "$(v3_orange)"
search-focused-match-foreground = "$(d1_white)"

selection-background            = "$(v3_black)"
selection-foreground            = "$(d1_white)"
