"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$shell\
$directory\
$git_branch\
$git_commit\
$git_status\
$fill\
$cmd_duration\
$python\
$time\
$status
$character
"""
palette = "mytilus_light"

[palettes.mytilus_light]
d0_black      = "#202924"
d0_white      = "#2C2429"
d1_black      = "#2A332E"
d1_white      = "#362D33"
d2_black      = "#343D38"
d2_white      = "#40383D"
d3_black      = "#3E4842"
d3_white      = "#4B4247"
d3_red        = "#742049"
d3_orange     = "#752821"
d3_yellow     = "#633B02"
d3_chartreuse = "#404A23"
d3_green      = "#154F4D"
d3_cyan       = "#1B486E"
d3_blue       = "#43397A"
d3_purple     = "#62296B"
v0_black      = "#CEE9D9"
v0_white      = "#F2D9E9"
v1_black      = "#C1DCCC"
v1_white      = "#E5CCDB"
v2_black      = "#B5CFC0"
v2_white      = "#D8BFCE"
v3_black      = "#A8C2B3"
v3_white      = "#CBB2C2"
v2_red        = "#FDABCD"
v2_orange     = "#FDB1AA"
v2_yellow     = "#E8BE9C"
v2_chartreuse = "#C7CBAD"
v2_green      = "#ABD0D0"
v2_cyan       = "#ACCAF1"
v2_blue       = "#C8BDFD"
v2_purple     = "#E8B1EE"
error         = "#742049"
warn          = "#633B02"
ok            = "#154F4D"
info          = "#62296B"
hint          = "#43397A"
add           = "#404A23"
delete        = "#742049"
change        = "#633B02"
bar0          = "#2A332E"
bar1          = "#D8BFCE"

[python]
disabled       = false
symbol         = " "
version_format = '${raw}'
style          = 'bold fg:d1_black bg:bar1'
format         = '[ [$symbol](fg:d1_black bg:bar1)${version} (\($virtualenv\)) ]($style)'

[shell]
disabled       = false
bash_indicator = "bash"
zsh_indicator  = "%"
nu_indicator   = ">"
fish_indicator = ""
style          = 'bold fg:v1_white bg:bar0'
format         = '[| $indicator ]($style)'

[fill]
symbol = ' '

[os]
disabled = false
style    = 'bold fg:v1_white bg:bar0'
format   = '[ $symbol ]($style)'

[os.symbols]
Arch     = ""
Gentoo   = ""
Linux    = ""
NixOS    = ""
Raspbian = ""
Void     = ""
Windows  = ""

[character]
disabled       = false
success_symbol = '[λ](bold ok) '
error_symbol   = '[λ](bold error) '

[time]
disabled        = false
format          = '[  $time |]($style)'
style           = 'bold fg:v1_white bg:bar0'
time_format     = '%R'
utc_time_offset = 'local'

[cmd_duration]
min_time          = 0
show_milliseconds = true
style             = 'bold fg:d1_black bg:bar1'
format            = '[ $duration |]($style)'

[git_branch]
symbol            = ' '
style             = 'bold fg:d1_black bg:bar1'
truncation_length = 22
truncation_symbol = '…'
format            = '[| $symbol$branch(:$remote_branch)]($style)'

[git_commit]
commit_hash_length = 7
tag_symbol         = '󰓹 '
only_detached      = false
tag_disabled       = false
style              = 'bold fg:info bg:bar1'
format             = '[ $tag\($hash\)]($style)'

[git_status]
format      = "[$ahead_behind$all_status ](fg:v3_white bg:bar1)"
diverged    = "[  $ahead_count $behind_count](fg:info bg:bar1)"
ahead       = "[  $count](fg:add bg:bar1)"
behind      = "[  $count](fg:delete bg:bar1)"
conflicted  = "[ 󰵖 $count](fg:error bg:bar1)"
stashed     = "[ 󰦕 $count](fg:warn bg:bar1)"
deleted     = "[  $count](fg:delete bg:bar1)"
renamed     = "[  $count](fg:change bg:bar1)"
modified    = "[  $count](fg:change bg:bar1)"
typechanged = "[ 󰴝 $count](fg:change bg:bar1)"
staged      = "[ 󰗡 $count](fg:ok bg:bar1)"
untracked   = "[ ◌ $count](fg:info bg:bar1)"

[status]
disabled              = false
style                 = 'bold fg:v1_white bg:bar0'
symbol                = ' '
success_symbol        = ' '
not_executable_symbol = ' '
not_found_symbol      = ' '
sigint_symbol         = ' '
signal_symbol         = ' '
map_symbol            = true
format                = '[ $symbol$common_meaning$status$signal_name$signal_number ]($style)'

[directory]
read_only                 = " "
fish_style_pwd_dir_length = 2
read_only_style           = 'bold fg:d1_black bg:bar1'
style                     = 'bold fg:d1_black bg:bar1'
format                    = '[ $read_only($read_only_style)$path ]($style)'
