"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$shell\
$directory\
$git_branch\
$git_commit\
$git_status\
$fill\
$cmd_duration\
$python\
$time\
$status
$character
"""
palette = "mytilus_light"

[palettes.mytilus_light]
d0_black      = "#35343A"
d0_white      = "#353630"
d1_black      = "#3A3A3F"
d1_white      = "#3A3B35"
d2_black      = "#403F45"
d2_white      = "#40403A"
d3_black      = "#45444A"
d3_white      = "#454640"
d3_red        = "#633443"
d3_orange     = "#643824"
d3_yellow     = "#544310"
d3_chartreuse = "#344D26"
d3_green      = "#025146"
d3_cyan       = "#094C61"
d3_blue       = "#36436B"
d3_purple     = "#53395F"
v0_black      = "#EEEDF5"
v0_white      = "#EEEFE8"
v1_black      = "#E1E0E8"
v1_white      = "#E1E2DB"
v2_black      = "#D4D3DA"
v2_white      = "#D4D5CE"
v3_black      = "#BEBDC4"
v3_white      = "#BDBEB7"
v2_red        = "#F7C4D2"
v2_orange     = "#F7C9B4"
v2_yellow     = "#E3D3A8"
v2_chartreuse = "#C4DEB6"
v2_green      = "#A9E2D6"
v2_cyan       = "#AADDF2"
v2_blue       = "#C5D3FD"
v2_purple     = "#E3C9F0"
error         = "#633443"
warn          = "#544310"
ok            = "#025146"
info          = "#53395F"
hint          = "#36436B"
add           = "#344D26"
delete        = "#633443"
change        = "#544310"
bar0          = "#3A3A3F"
bar1          = "#D4D5CE"

[python]
disabled       = false
symbol         = " "
version_format = '${raw}'
style          = 'bold fg:d1_black bg:bar1'
format         = '[ [$symbol](fg:d1_black bg:bar1)${version} (\($virtualenv\)) ]($style)'

[shell]
disabled       = false
bash_indicator = "bash"
zsh_indicator  = "%"
nu_indicator   = ">"
fish_indicator = ""
style          = 'bold fg:v1_white bg:bar0'
format         = '[| $indicator ]($style)'

[fill]
symbol = ' '

[os]
disabled = false
style    = 'bold fg:v1_white bg:bar0'
format   = '[ $symbol ]($style)'

[os.symbols]
Arch     = ""
Gentoo   = ""
Linux    = ""
NixOS    = ""
Raspbian = ""
Void     = ""
Windows  = ""

[character]
disabled       = false
success_symbol = '[λ](bold ok) '
error_symbol   = '[λ](bold error) '

[time]
disabled        = false
format          = '[  $time |]($style)'
style           = 'bold fg:v1_white bg:bar0'
time_format     = '%R'
utc_time_offset = 'local'

[cmd_duration]
min_time          = 0
show_milliseconds = true
style             = 'bold fg:d1_black bg:bar1'
format            = '[ $duration |]($style)'

[git_branch]
symbol            = ' '
style             = 'bold fg:d1_black bg:bar1'
truncation_length = 22
truncation_symbol = '…'
format            = '[| $symbol$branch(:$remote_branch)]($style)'

[git_commit]
commit_hash_length = 7
tag_symbol         = '󰓹 '
only_detached      = false
tag_disabled       = false
style              = 'bold fg:info bg:bar1'
format             = '[ $tag\($hash\)]($style)'

[git_status]
format      = "[$ahead_behind$all_status ](fg:v3_white bg:bar1)"
diverged    = "[  $ahead_count $behind_count](fg:info bg:bar1)"
ahead       = "[  $count](fg:add bg:bar1)"
behind      = "[  $count](fg:delete bg:bar1)"
conflicted  = "[ 󰵖 $count](fg:error bg:bar1)"
stashed     = "[ 󰦕 $count](fg:warn bg:bar1)"
deleted     = "[  $count](fg:delete bg:bar1)"
renamed     = "[  $count](fg:change bg:bar1)"
modified    = "[  $count](fg:change bg:bar1)"
typechanged = "[ 󰴝 $count](fg:change bg:bar1)"
staged      = "[ 󰗡 $count](fg:ok bg:bar1)"
untracked   = "[ ◌ $count](fg:info bg:bar1)"

[status]
disabled              = false
style                 = 'bold fg:v1_white bg:bar0'
symbol                = ' '
success_symbol        = ' '
not_executable_symbol = ' '
not_found_symbol      = ' '
sigint_symbol         = ' '
signal_symbol         = ' '
map_symbol            = true
format                = '[ $symbol$common_meaning$status$signal_name$signal_number ]($style)'

[directory]
read_only                 = " "
fish_style_pwd_dir_length = 2
read_only_style           = 'bold fg:d1_black bg:bar1'
style                     = 'bold fg:d1_black bg:bar1'
format                    = '[ $read_only($read_only_style)$path ]($style)'
