"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$shell\
$directory\
$git_branch\
$git_commit\
$git_status\
$fill\
$cmd_duration\
$python\
$time\
$status
$character
"""
palette = "mytilus_dark"

[palettes.mytilus_dark]
d0_black      = "#DFDCE7"
d0_white      = "#DEDFD4"
d1_black      = "#D5D2DD"
d1_white      = "#D4D5CA"
d2_black      = "#C8C5D0"
d2_white      = "#C7C8BD"
d3_black      = "#BEBCC6"
d3_white      = "#BEBFB4"
d3_red        = "#E5ADB2"
d3_orange     = "#E5B18E"
d3_yellow     = "#CFBD7E"
d3_chartreuse = "#ABC990"
d3_green      = "#8BCEB6"
d3_cyan       = "#8CC9D7"
d3_blue       = "#ACBEE3"
d3_purple     = "#CFB2D4"
v0_black      = "#25232B"
v0_white      = "#24251D"
v1_black      = "#2E2C35"
v1_white      = "#2E2F26"
v2_black      = "#39363F"
v2_white      = "#383930"
v3_black      = "#43414A"
v3_white      = "#42433A"
v2_red        = "#4F2D2F"
v2_orange     = "#502F14"
v2_yellow     = "#433701"
v2_chartreuse = "#2C3F15"
v2_green      = "#0D4231"
v2_cyan       = "#0F3F46"
v2_blue       = "#2C384E"
v2_purple     = "#423145"
error         = "#E5ADB2"
warn          = "#CFBD7E"
ok            = "#8BCEB6"
info          = "#CFB2D4"
hint          = "#ACBEE3"
add           = "#ABC990"
delete        = "#E5ADB2"
change        = "#CFBD7E"
bar0          = "#D5D2DD"
bar1          = "#383930"

[python]
disabled       = false
symbol         = " "
version_format = '${raw}'
style          = 'bold fg:d1_black bg:bar1'
format         = '[ [$symbol](fg:d1_black bg:bar1)${version} (\($virtualenv\)) ]($style)'

[shell]
disabled       = false
bash_indicator = "bash"
zsh_indicator  = "%"
nu_indicator   = ">"
fish_indicator = ""
style          = 'bold fg:v1_white bg:bar0'
format         = '[| $indicator ]($style)'

[fill]
symbol = ' '

[os]
disabled = false
style    = 'bold fg:v1_white bg:bar0'
format   = '[ $symbol ]($style)'

[os.symbols]
Arch     = ""
Gentoo   = ""
Linux    = ""
NixOS    = ""
Raspbian = ""
Void     = ""
Windows  = ""

[character]
disabled       = false
success_symbol = '[λ](bold ok) '
error_symbol   = '[λ](bold error) '

[time]
disabled        = false
format          = '[  $time |]($style)'
style           = 'bold fg:v1_white bg:bar0'
time_format     = '%R'
utc_time_offset = 'local'

[cmd_duration]
min_time          = 0
show_milliseconds = true
style             = 'bold fg:d1_black bg:bar1'
format            = '[ $duration |]($style)'

[git_branch]
symbol            = ' '
style             = 'bold fg:d1_black bg:bar1'
truncation_length = 22
truncation_symbol = '…'
format            = '[| $symbol$branch(:$remote_branch)]($style)'

[git_commit]
commit_hash_length = 7
tag_symbol         = '󰓹 '
only_detached      = false
tag_disabled       = false
style              = 'bold fg:info bg:bar1'
format             = '[ $tag\($hash\)]($style)'

[git_status]
format      = "[$ahead_behind$all_status ](fg:v3_white bg:bar1)"
diverged    = "[  $ahead_count $behind_count](fg:info bg:bar1)"
ahead       = "[  $count](fg:add bg:bar1)"
behind      = "[  $count](fg:delete bg:bar1)"
conflicted  = "[ 󰵖 $count](fg:error bg:bar1)"
stashed     = "[ 󰦕 $count](fg:warn bg:bar1)"
deleted     = "[  $count](fg:delete bg:bar1)"
renamed     = "[  $count](fg:change bg:bar1)"
modified    = "[  $count](fg:change bg:bar1)"
typechanged = "[ 󰴝 $count](fg:change bg:bar1)"
staged      = "[ 󰗡 $count](fg:ok bg:bar1)"
untracked   = "[ ◌ $count](fg:info bg:bar1)"

[status]
disabled              = false
style                 = 'bold fg:v1_white bg:bar0'
symbol                = ' '
success_symbol        = ' '
not_executable_symbol = ' '
not_found_symbol      = ' '
sigint_symbol         = ' '
signal_symbol         = ' '
map_symbol            = true
format                = '[ $symbol$common_meaning$status$signal_name$signal_number ]($style)'

[directory]
read_only                 = " "
fish_style_pwd_dir_length = 2
read_only_style           = 'bold fg:d1_black bg:bar1'
style                     = 'bold fg:d1_black bg:bar1'
format                    = '[ $read_only($read_only_style)$path ]($style)'
