"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$shell\
$directory\
$git_branch\
$git_commit\
$git_status\
$fill\
$cmd_duration\
$python\
$time\
$status
$character
"""
palette = "mytilus_light"

[palettes.mytilus_light]
d0_black      = "#39363F"
d0_white      = "#383930"
d1_black      = "#403E47"
d1_white      = "#404138"
d2_black      = "#48464F"
d2_white      = "#48493F"
d3_black      = "#504E57"
d3_white      = "#505147"
d3_red        = "#6F4046"
d3_orange     = "#704423"
d3_yellow     = "#5F4E09"
d3_chartreuse = "#3F5925"
d3_green      = "#155D49"
d3_cyan       = "#185965"
d3_blue       = "#404F6F"
d3_purple     = "#5E4663"
v0_black      = "#F6F3FE"
v0_white      = "#F5F6EB"
v1_black      = "#E9E6F1"
v1_white      = "#E8E9DE"
v2_black      = "#DCD9E4"
v2_white      = "#DBDCD1"
v3_black      = "#CFCCD7"
v3_white      = "#CECFC4"
v2_red        = "#FECCCF"
v2_orange     = "#FED0B0"
v2_yellow     = "#EADBA3"
v2_chartreuse = "#CAE5B2"
v2_green      = "#B0EAD2"
v2_cyan       = "#B0E5F0"
v2_blue       = "#CBDBFA"
v2_purple     = "#EAD1ED"
error         = "#6F4046"
warn          = "#5F4E09"
ok            = "#155D49"
info          = "#5E4663"
hint          = "#404F6F"
add           = "#3F5925"
delete        = "#6F4046"
change        = "#5F4E09"
bar0          = "#403E47"
bar1          = "#DBDCD1"

[python]
disabled       = false
symbol         = " "
version_format = '${raw}'
style          = 'bold fg:d1_black bg:bar1'
format         = '[ [$symbol](fg:d1_black bg:bar1)${version} (\($virtualenv\)) ]($style)'

[shell]
disabled       = false
bash_indicator = "bash"
zsh_indicator  = "%"
nu_indicator   = ">"
fish_indicator = ""
style          = 'bold fg:v1_white bg:bar0'
format         = '[| $indicator ]($style)'

[fill]
symbol = ' '

[os]
disabled = false
style    = 'bold fg:v1_white bg:bar0'
format   = '[ $symbol ]($style)'

[os.symbols]
Arch     = ""
Gentoo   = ""
Linux    = ""
NixOS    = ""
Raspbian = ""
Void     = ""
Windows  = ""

[character]
disabled       = false
success_symbol = '[λ](bold ok) '
error_symbol   = '[λ](bold error) '

[time]
disabled        = false
format          = '[  $time |]($style)'
style           = 'bold fg:v1_white bg:bar0'
time_format     = '%R'
utc_time_offset = 'local'

[cmd_duration]
min_time          = 0
show_milliseconds = true
style             = 'bold fg:d1_black bg:bar1'
format            = '[ $duration |]($style)'

[git_branch]
symbol            = ' '
style             = 'bold fg:d1_black bg:bar1'
truncation_length = 22
truncation_symbol = '…'
format            = '[| $symbol$branch(:$remote_branch)]($style)'

[git_commit]
commit_hash_length = 7
tag_symbol         = '󰓹 '
only_detached      = false
tag_disabled       = false
style              = 'bold fg:info bg:bar1'
format             = '[ $tag\($hash\)]($style)'

[git_status]
format      = "[$ahead_behind$all_status ](fg:v3_white bg:bar1)"
diverged    = "[  $ahead_count $behind_count](fg:info bg:bar1)"
ahead       = "[  $count](fg:add bg:bar1)"
behind      = "[  $count](fg:delete bg:bar1)"
conflicted  = "[ 󰵖 $count](fg:error bg:bar1)"
stashed     = "[ 󰦕 $count](fg:warn bg:bar1)"
deleted     = "[  $count](fg:delete bg:bar1)"
renamed     = "[  $count](fg:change bg:bar1)"
modified    = "[  $count](fg:change bg:bar1)"
typechanged = "[ 󰴝 $count](fg:change bg:bar1)"
staged      = "[ 󰗡 $count](fg:ok bg:bar1)"
untracked   = "[ ◌ $count](fg:info bg:bar1)"

[status]
disabled              = false
style                 = 'bold fg:v1_white bg:bar0'
symbol                = ' '
success_symbol        = ' '
not_executable_symbol = ' '
not_found_symbol      = ' '
sigint_symbol         = ' '
signal_symbol         = ' '
map_symbol            = true
format                = '[ $symbol$common_meaning$status$signal_name$signal_number ]($style)'

[directory]
read_only                 = " "
fish_style_pwd_dir_length = 2
read_only_style           = 'bold fg:d1_black bg:bar1'
style                     = 'bold fg:d1_black bg:bar1'
format                    = '[ $read_only($read_only_style)$path ]($style)'
