"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$shell\
$directory\
$git_branch\
$git_commit\
$git_status\
$fill\
$cmd_duration\
$python\
$time\
$status
$character
"""
palette = "mytilus_light"

[palettes.mytilus_light]
d0_black      = "#3B3338"
d0_white      = "#2F3832"
d1_black      = "#433A40"
d1_white      = "#37403A"
d2_black      = "#4B4248"
d2_white      = "#3F4842"
d3_black      = "#534A50"
d3_white      = "#47504A"
d3_red        = "#70384E"
d3_orange     = "#713C30"
d3_yellow     = "#614820"
d3_chartreuse = "#435332"
d3_green      = "#235751"
d3_cyan       = "#26526C"
d3_blue       = "#454876"
d3_purple     = "#613D6A"
v0_black      = "#F6EBF2"
v0_white      = "#E7F2EA"
v1_black      = "#E8DEE5"
v1_white      = "#DAE4DD"
v2_black      = "#DBD1D8"
v2_white      = "#CDD7D0"
v3_black      = "#CEC4CB"
v3_white      = "#C0CAC3"
v2_red        = "#E5CDCF"
v2_orange     = "#E5D0BB"
v2_yellow     = "#D7D7B3"
v2_chartreuse = "#C1DEBD"
v2_green      = "#B0E0D1"
v2_cyan       = "#B1DEE5"
v2_blue       = "#C2D7EC"
v2_purple     = "#D7D0E3"
error         = "#70384E"
warn          = "#614820"
ok            = "#235751"
info          = "#613D6A"
hint          = "#454876"
add           = "#435332"
delete        = "#70384E"
change        = "#614820"
bar0          = "#433A40"
bar1          = "#CDD7D0"

[python]
disabled       = false
symbol         = " "
version_format = '${raw}'
style          = 'bold fg:d1_black bg:bar1'
format         = '[ [$symbol](fg:d1_black bg:bar1)${version} (\($virtualenv\)) ]($style)'

[shell]
disabled       = false
bash_indicator = "bash"
zsh_indicator  = "%"
nu_indicator   = ">"
fish_indicator = ""
style          = 'bold fg:v1_white bg:bar0'
format         = '[| $indicator ]($style)'

[fill]
symbol = ' '

[os]
disabled = false
style    = 'bold fg:v1_white bg:bar0'
format   = '[ $symbol ]($style)'

[os.symbols]
Arch     = ""
Gentoo   = ""
Linux    = ""
NixOS    = ""
Raspbian = ""
Void     = ""
Windows  = ""

[character]
disabled       = false
success_symbol = '[λ](bold ok) '
error_symbol   = '[λ](bold error) '

[time]
disabled        = false
format          = '[  $time |]($style)'
style           = 'bold fg:v1_white bg:bar0'
time_format     = '%R'
utc_time_offset = 'local'

[cmd_duration]
min_time          = 0
show_milliseconds = true
style             = 'bold fg:d1_black bg:bar1'
format            = '[ $duration |]($style)'

[git_branch]
symbol            = ' '
style             = 'bold fg:d1_black bg:bar1'
truncation_length = 22
truncation_symbol = '…'
format            = '[| $symbol$branch(:$remote_branch)]($style)'

[git_commit]
commit_hash_length = 7
tag_symbol         = '󰓹 '
only_detached      = false
tag_disabled       = false
style              = 'bold fg:info bg:bar1'
format             = '[ $tag\($hash\)]($style)'

[git_status]
format      = "[$ahead_behind$all_status ](fg:v3_white bg:bar1)"
diverged    = "[  $ahead_count $behind_count](fg:info bg:bar1)"
ahead       = "[  $count](fg:add bg:bar1)"
behind      = "[  $count](fg:delete bg:bar1)"
conflicted  = "[ 󰵖 $count](fg:error bg:bar1)"
stashed     = "[ 󰦕 $count](fg:warn bg:bar1)"
deleted     = "[  $count](fg:delete bg:bar1)"
renamed     = "[  $count](fg:change bg:bar1)"
modified    = "[  $count](fg:change bg:bar1)"
typechanged = "[ 󰴝 $count](fg:change bg:bar1)"
staged      = "[ 󰗡 $count](fg:ok bg:bar1)"
untracked   = "[ ◌ $count](fg:info bg:bar1)"

[status]
disabled              = false
style                 = 'bold fg:v1_white bg:bar0'
symbol                = ' '
success_symbol        = ' '
not_executable_symbol = ' '
not_found_symbol      = ' '
sigint_symbol         = ' '
signal_symbol         = ' '
map_symbol            = true
format                = '[ $symbol$common_meaning$status$signal_name$signal_number ]($style)'

[directory]
read_only                 = " "
fish_style_pwd_dir_length = 2
read_only_style           = 'bold fg:d1_black bg:bar1'
style                     = 'bold fg:d1_black bg:bar1'
format                    = '[ $read_only($read_only_style)$path ]($style)'
