"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$shell\
$directory\
$git_branch\
$git_commit\
$git_status\
$fill\
$cmd_duration\
$python\
$time\
$status
$character
"""
palette = "mytilus_light"

[palettes.mytilus_light]
d0_black      = "#2E2D35"
d0_white      = "#2E2F26"
d1_black      = "#38373F"
d1_white      = "#383930"
d2_black      = "#42414A"
d2_white      = "#42433A"
d3_black      = "#4D4C55"
d3_white      = "#4D4E45"
d3_red        = "#6F3E32"
d3_orange     = "#67460E"
d3_yellow     = "#4E510F"
d3_chartreuse = "#285934"
d3_green      = "#035956"
d3_cyan       = "#2A526A"
d3_blue       = "#4E4869"
d3_purple     = "#653F53"
v0_black      = "#EEEDF8"
v0_white      = "#EEF0E4"
v1_black      = "#E1E0EB"
v1_white      = "#E1E2D7"
v2_black      = "#D1CFDA"
v2_white      = "#D1D2C7"
v3_black      = "#C4C2CD"
v3_white      = "#C4C5BA"
v2_red        = "#F6C4B5"
v2_orange     = "#ECCB9D"
v2_yellow     = "#D1D79E"
v2_chartreuse = "#B1DFB8"
v2_green      = "#A2DFD9"
v2_cyan       = "#B2D7EE"
v2_blue       = "#D1CCED"
v2_purple     = "#ECC4D6"
error         = "#6F3E32"
warn          = "#4E510F"
ok            = "#035956"
info          = "#653F53"
hint          = "#4E4869"
add           = "#285934"
delete        = "#6F3E32"
change        = "#4E510F"
bar0          = "#38373F"
bar1          = "#D1D2C7"

[python]
disabled       = false
symbol         = " "
version_format = '${raw}'
style          = 'bold fg:d1_black bg:bar1'
format         = '[ [$symbol](fg:d1_black bg:bar1)${version} (\($virtualenv\)) ]($style)'

[shell]
disabled       = false
bash_indicator = "bash"
zsh_indicator  = "%"
nu_indicator   = ">"
fish_indicator = ""
style          = 'bold fg:v1_white bg:bar0'
format         = '[| $indicator ]($style)'

[fill]
symbol = ' '

[os]
disabled = false
style    = 'bold fg:v1_white bg:bar0'
format   = '[ $symbol ]($style)'

[os.symbols]
Arch     = ""
Gentoo   = ""
Linux    = ""
NixOS    = ""
Raspbian = ""
Void     = ""
Windows  = ""

[character]
disabled       = false
success_symbol = '[λ](bold ok) '
error_symbol   = '[λ](bold error) '

[time]
disabled        = false
format          = '[  $time |]($style)'
style           = 'bold fg:v1_white bg:bar0'
time_format     = '%R'
utc_time_offset = 'local'

[cmd_duration]
min_time          = 0
show_milliseconds = true
style             = 'bold fg:d1_black bg:bar1'
format            = '[ $duration |]($style)'

[git_branch]
symbol            = ' '
style             = 'bold fg:d1_black bg:bar1'
truncation_length = 22
truncation_symbol = '…'
format            = '[| $symbol$branch(:$remote_branch)]($style)'

[git_commit]
commit_hash_length = 7
tag_symbol         = '󰓹 '
only_detached      = false
tag_disabled       = false
style              = 'bold fg:info bg:bar1'
format             = '[ $tag\($hash\)]($style)'

[git_status]
format      = "[$ahead_behind$all_status ](fg:v3_white bg:bar1)"
diverged    = "[  $ahead_count $behind_count](fg:info bg:bar1)"
ahead       = "[  $count](fg:add bg:bar1)"
behind      = "[  $count](fg:delete bg:bar1)"
conflicted  = "[ 󰵖 $count](fg:error bg:bar1)"
stashed     = "[ 󰦕 $count](fg:warn bg:bar1)"
deleted     = "[  $count](fg:delete bg:bar1)"
renamed     = "[  $count](fg:change bg:bar1)"
modified    = "[  $count](fg:change bg:bar1)"
typechanged = "[ 󰴝 $count](fg:change bg:bar1)"
staged      = "[ 󰗡 $count](fg:ok bg:bar1)"
untracked   = "[ ◌ $count](fg:info bg:bar1)"

[status]
disabled              = false
style                 = 'bold fg:v1_white bg:bar0'
symbol                = ' '
success_symbol        = ' '
not_executable_symbol = ' '
not_found_symbol      = ' '
sigint_symbol         = ' '
signal_symbol         = ' '
map_symbol            = true
format                = '[ $symbol$common_meaning$status$signal_name$signal_number ]($style)'

[directory]
read_only                 = " "
fish_style_pwd_dir_length = 2
read_only_style           = 'bold fg:d1_black bg:bar1'
style                     = 'bold fg:d1_black bg:bar1'
format                    = '[ $read_only($read_only_style)$path ]($style)'
